export const W=390,H=760,BUILD='reclaim-proof-001.2';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
export function event(s,type,data={}){s.events.push({t:+s.t.toFixed(3),type,...data});if(s.events.length>700)s.events.shift()}
function battery(id,x,y){return{id,x,y,r:25,alive:true,phase:id==='left'?'aim':'dormant',clock:id==='left'?1.2:11,heat:0,limit:id==='left'?3:8,shotsFired:0,sourceId:'battery-'+id,lock:null,flash:0,capturedAt:null,opportunity:false}}
function guard(id,x,y,group='patrol',heavy=false){return{id,x,y,a:0,r:heavy?22:17,hp:heavy?6:3.8,heavy,entry:.65,cd:1.7,hit:0,lock:null,group,attacks:0}}
export function create(){return{build:BUILD,t:0,status:'ready',p:{x:230,y:622,a:0,hp:3,inv:0,bump:0,left:false,right:false,front:0,leftCD:0,rightCD:0},covers:[battery('left',95,510),battery('right',302,530)],walls:[{x:120,y:366,w:39,h:26},{x:231,y:366,w:39,h:26}],enemies:[guard(1,45,455,'left-escort'),guard(2,45,555,'left-escort')],shots:[],fx:[],events:[],spawn:9,nextId:3,kills:0,exit:false,cause:'',volley:0,lastWeapon:'',captured:{},reversal:false,optionalAttempt:false,travel:0}}
export function start(s){if(s.status==='ready'){s.status='playing';event(s,'start',{actor:'UNCLASSIFIED',build:BUILD})}}
export function pause(s,reason='button'){if(s.status==='playing'){s.status='paused';event(s,'pause',{reason})}}
export function resume(s){if(s.status==='paused'){s.status='playing';event(s,'resume')}}
export function parts(p){const out=[{x:p.x,y:p.y,r:17}];for(const [key,sign]of [['left',-1],['right',1]])if(p[key])out.push({x:p.x+Math.cos(p.a)*sign*26,y:p.y+Math.sin(p.a)*sign*26,r:13});return out}
function rectHit(c,r){return Math.hypot(c.x-clamp(c.x,r.x,r.x+r.w),c.y-clamp(c.y,r.y,r.y+r.h))<c.r}
function solid(s,c,ignore=null){return c.x-c.r<16||c.x+c.r>374||c.y-c.r<106||c.y+c.r>707||s.walls.some(r=>rectHit(c,r))||s.covers.some(v=>v.alive&&v.id!==ignore&&distance(c,v)<c.r+v.r)}
export function blocked(s,p){return parts(p).some(c=>solid(s,c))}
function burst(s,x,y,kind,n=8){for(let i=0;i<n;i++)s.fx.push({x,y,vx:Math.cos(i*2.399)*(35+i*5),vy:Math.sin(i*2.399)*(35+i*5),life:.6,max:.6,kind,i});s.fx=s.fx.slice(-150)}
export function capture(s){for(const c of s.covers){if(!c.alive||c.phase!=='overheat'||c.shotsFired<c.limit||distance(s.p,c)>=57)continue;c.alive=false;c.phase='taken';c.capturedAt=s.t;s.p[c.id]=true;s.p.x=clamp(s.p.x,16+(s.p.left?39:17),374-(s.p.right?39:17));s.captured[c.id]={at:s.t,travel:s.travel,sourceId:c.sourceId,threats:s.enemies.filter(e=>e.entry<=0&&e.attacks>0).map(e=>e.id),firstUse:false};event(s,'capture',{side:c.id,from:{x:c.x,y:c.y},sourceId:c.sourceId,hostileShots:c.shotsFired,coverRemoved:true,exitAvailable:s.exit,preexistingThreats:s.captured[c.id].threats});burst(s,c.x,c.y,'capture',18)}}
export function hurt(s,cause,source={}){if(s.status!=='playing'||s.p.inv>0)return;s.p.hp--;s.p.inv=1.7;s.cause=cause;s.fatal={x:s.p.x,y:s.p.y,...source};event(s,'damage',{cause,hp:s.p.hp,...source});burst(s,s.p.x,s.p.y,'damage',16);if(s.p.hp<=0){s.status='lost';event(s,'lost',{cause,owned:['left','right'].filter(k=>s.p[k]),exitAvailable:s.exit,untaken:s.covers.filter(c=>c.alive).map(c=>c.id)})}}
function shot(s,x,y,angle,kind,enemy,sourceId,speed){s.shots.push({x,y,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed,r:kind==='right'?6:kind==='left'?4:3,life:kind==='left'?1.65:4,kind,enemy,sourceOwner:enemy?'hostile':'player',sourceId,originX:x,originY:y,damage:kind==='front'?.45:kind==='right'?2.6:1.3,hit:[]})}
export function fire(s,kind){const p=s.p,a=p.a-Math.PI/2+(kind==='left'?-Math.PI/2:kind==='right'?Math.PI/2:0),origin=s.captured[kind];s.volley++;s.lastWeapon=kind;for(const delta of kind==='left'?[-.23,0,.23]:[0])shot(s,p.x+Math.cos(a)*31,p.y+Math.sin(a)*31,a+delta,kind,false,origin?.sourceId||'front-gun',kind==='right'?460:kind==='left'?340:300);if(origin&&!origin.firstUse){origin.firstUse=true;event(s,'first-use',{weapon:kind,sourceId:origin.sourceId,movedAfterCapture:s.travel-origin.travel})}}
function updateBattery(s,c,dt){if(!c.alive)return;c.flash=Math.max(0,c.flash-dt);c.clock-=dt;
 if(c.phase==='dormant'&&c.clock<=0){c.phase='aim';c.clock=1.1;c.lock={x:s.p.x,y:s.p.y};event(s,'power-preview',{sourceId:c.sourceId,weapon:c.id})}
 if(c.phase==='aim'&&!c.lock)c.lock={x:s.p.x,y:s.p.y};
 if(c.clock>0)return;
 if(c.phase==='aim'){const a=Math.atan2(c.lock.y-c.y,c.lock.x-c.x);for(const delta of c.id==='left'?[-.23,0,.23]:[0])shot(s,c.x+Math.cos(a)*32,c.y+Math.sin(a)*32,a+delta,c.id,true,c.sourceId,c.id==='left'?155:390);c.heat++;c.shotsFired++;event(s,'hostile-fire',{sourceId:c.sourceId,weapon:c.id,pattern:c.id==='left'?'three-shot-fan':'piercing-line',aim:c.lock,cycleShot:c.heat});c.phase=c.heat>=c.limit?'cooldown':'reload';c.clock=c.heat>=c.limit?.8:c.id==='left'?.3:3.3;c.lock=null;}
 else if(c.phase==='reload'){c.phase='aim';c.clock=c.id==='left'?1:1.1;c.lock={x:s.p.x,y:s.p.y}}
 else if(c.phase==='cooldown'){c.phase='overheat';c.clock=c.id==='left'?5.5:12;event(s,'capture-window',{side:c.id,sourceId:c.sourceId,afterActualShots:c.shotsFired,until:+(s.t+c.clock).toFixed(2)});burst(s,c.x,c.y,'cover',8)}
 else if(c.phase==='overheat'){c.heat=0;c.phase='aim';c.clock=1.2;c.lock={x:s.p.x,y:s.p.y};event(s,'window-closed',{sourceId:c.sourceId})}
}
function spawn(s){const id=s.nextId++,heavy=s.t>=30&&id%3===0;const spots=[[45,230],[338,210],[338,635],[50,655],[65,440],[326,440]];const order=spots.map((_,i)=>spots[(id+i)%spots.length]);const choice=order.find(([x,y])=>Math.hypot(x-s.p.x,y-s.p.y)>125&&!s.enemies.some(e=>Math.hypot(e.x-x,e.y-y)<48));if(!choice)return;const [x,y]=choice;s.enemies.push(guard(id,x,y,'patrol',heavy));event(s,'enemy-entry',{id,heavy,x,y})}
function displace(s,e,b){let moved=0;for(let i=0;i<7;i++){const q={x:e.x+b.vx/340*6,y:e.y+b.vy/340*6,r:e.r};if(solid(s,q))break;moved+=distance(e,q);e.x=q.x;e.y=q.y}return moved}
export function step(s,dt,target=null){if(s.status!=='playing'||dt<=0||dt>.1)return;s.t+=dt;const p=s.p;p.inv=Math.max(0,p.inv-dt);p.bump=Math.max(0,p.bump-dt);
 for(const c of s.covers)updateBattery(s,c,dt);
 capture(s);
 const before={x:p.x,y:p.y};if(target){const dx=target.x-p.x,dy=target.y-p.y,d=Math.hypot(dx,dy);if(d>3){const speed=Math.min(d,215*dt);let q={...p,x:p.x+dx/d*speed};if(!blocked(s,q))p.x=q.x;else if(Math.abs(dx)>3)p.bump=.15;q={...p,y:p.y+dy/d*speed};if(!blocked(s,q))p.y=q.y;else if(Math.abs(dy)>3)p.bump=.15;}}s.travel+=distance(before,p);
 for(const [kind,cd,interval]of [['front','front',.9],['left','leftCD',.6],['right','rightCD',1.05]]){p[cd]-=dt;if((kind==='front'||p[kind])&&p[cd]<=0){p[cd]=interval;fire(s,kind)}}
 s.spawn-=dt;if(s.spawn<=0&&s.enemies.length<7){spawn(s);s.spawn=s.t<20?6:s.t<45?5.5:4.5}
 for(const e of s.enemies){if(e.entry>0){e.entry-=dt;continue}e.hit=Math.max(0,e.hit-dt);const d=distance(e,p),dx=(p.x-e.x)/(d||1),dy=(p.y-e.y)/(d||1);e.a=Math.atan2(dx,-dy);if(d>104){const q={x:e.x+dx*dt*(e.heavy?15:21),y:e.y+dy*dt*(e.heavy?15:21),r:e.r};if(!solid(s,q)){e.x=q.x;e.y=q.y}}e.cd-=dt;if(e.cd<.85&&!e.lock)e.lock={x:p.x,y:p.y};if(e.cd<=0){const a=Math.atan2(e.lock.y-e.y,e.lock.x-e.x);shot(s,e.x+Math.cos(a)*22,e.y+Math.sin(a)*22,a,'guard',true,'guard-'+e.id,e.heavy?125:110);e.attacks++;event(s,'hostile-fire',{sourceId:'guard-'+e.id,weapon:'guard',target:'player'});e.cd=e.heavy?3.4:4.2;e.lock=null}if(d<e.r+17)hurt(s,'撞上追击车',{sourceId:'guard-'+e.id,sourceX:e.x,sourceY:e.y})}
 for(const b of s.shots){b.life-=dt;const steps=Math.max(1,Math.ceil(Math.hypot(b.vx,b.vy)*dt/5));for(let i=0;i<steps&&b.life>0;i++){b.x+=b.vx*dt/steps;b.y+=b.vy*dt/steps;const shield=s.covers.find(c=>c.alive&&c.sourceId!==b.sourceId&&distance(b,c)<c.r+b.r);if(s.walls.some(r=>rectHit(b,r))||shield){if(shield){if(!shield.flash)event(s,'cover-block',{side:shield.id,sourceOwner:b.sourceOwner,sourceId:b.sourceId,weapon:b.kind});shield.flash=.3}b.life=0;burst(s,b.x,b.y,'cover',4);break}
 if(b.enemy){if(parts(p).some(c=>distance(c,b)<c.r+b.r)){b.life=0;hurt(s,b.kind==='left'?'被散射压制':b.kind==='right'?'被电炮贯穿':'被追击炮弹击中',{sourceId:b.sourceId,weapon:b.kind,sourceX:b.originX,sourceY:b.originY})}}
 else for(const e of s.enemies)if(e.entry<=0&&e.hp>0&&!b.hit.includes(e.id)&&distance(e,b)<e.r+b.r){const hitFrom={x:e.x,y:e.y};e.hp-=b.damage;e.hit=.2;b.hit.push(e.id);if(b.kind==='right'&&s.captured.right){(b.hitPoints??=[]).push({enemy:e.id,x:e.x,y:e.y});if(b.hit.length===2)event(s,'pierce-chain',{sourceId:b.sourceId,weapon:'right',points:b.hitPoints.map(p=>({...p}))})}if(b.kind!=='right')b.life=0;const moved=b.kind==='left'?displace(s,e,b):0,origin=s.captured[b.kind];if(origin&&origin.threats.includes(e.id)&&(moved>8||e.hp<=0)){event(s,'power-consequence',{sourceId:b.sourceId,weapon:b.kind,enemy:e.id,preexistingThreat:true,displacement:+moved.toFixed(1),destroyed:e.hp<=0,movedAfterCapture:+(s.travel-origin.travel).toFixed(1)});if(!s.reversal&&s.travel-origin.travel>=12){s.reversal=true;event(s,'reversal',{sourceId:b.sourceId,weapon:b.kind,originalThreat:e.id,from:hitFrom,to:{x:e.x,y:e.y},displacement:+moved.toFixed(1),destroyed:e.hp<=0,definition:'physical consequence after measured movement; emotional response UNKNOWN'});burst(s,e.x,e.y,'capture',22)}}burst(s,e.x,e.y,'hit',4);if(e.hp<=0){s.kills++;event(s,'destroy',{enemy:e.id,weapon:b.kind,sourceId:b.sourceId});burst(s,e.x,e.y,'destroy',14)}}}}
 s.enemies=s.enemies.filter(e=>e.hp>0);s.shots=s.shots.filter(b=>b.life>0&&b.x>-20&&b.x<410&&b.y>75&&b.y<750).slice(-140);for(const f of s.fx){f.life-=dt;f.x+=f.vx*dt;f.y+=f.vy*dt;f.vx*=.95;f.vy*=.95}s.fx=s.fx.filter(f=>f.life>0);
 if(s.t>=45&&!s.exit){s.exit=true;event(s,'exit-open',{requiresPickups:false,requiresKills:false})}
 const right=s.covers[1];if(s.exit&&right.alive&&right.phase==='overheat'&&!right.opportunity){right.opportunity=true;event(s,'optional-opportunity',{sourceId:right.sourceId,exitAvailable:true,windowUntil:+(s.t+right.clock).toFixed(2)})}
 if(s.exit&&right.alive&&!s.optionalAttempt&&distance(p,right)<115){s.optionalAttempt=true;event(s,'optional-approach',{sourceId:right.sourceId,exitAvailable:true,actor:'UNCLASSIFIED',intent:'UNKNOWN'})}
 if(s.status==='playing'&&s.exit&&distance(p,{x:195,y:133})<43){s.status='won';event(s,'won',{kills:s.kills,owned:['left','right'].filter(k=>p[k]),leftBehind:s.covers.filter(c=>c.alive).map(c=>c.id)});burst(s,p.x,p.y,'capture',32)}
 if(s.t>=90&&s.status==='playing'){s.status='lost';s.cause='撤离窗口关闭';event(s,'lost',{cause:s.cause,owned:['left','right'].filter(k=>p[k]),exitAvailable:s.exit})}
}
