import{create,start,pause,resume,step,event}from'./engine.mjs';import{loadArt,paint}from'./paint.js';import{createAudio}from'./audio.js';
const $=id=>document.getElementById(id),canvas=$('canvas'),ctx=canvas.getContext('2d'),audio=createAudio(),qa=new URLSearchParams(location.search).get('qa')==='1';
let state=create(),art=null,target=null,pointer=null,last=performance.now(),acc=0,seen=new Set(),ui='',qaAt=0,volley=0,runId=null,saved=0,wonAt=null;
if(qa)$('qa').classList.remove('hidden');
function clear(){target=null;pointer=null;acc=0}
function persist(){if(!runId||saved===state.events.length)return;saved=state.events.length;try{const key='reclaim-proof-001-local-events',runs=JSON.parse(sessionStorage.getItem(key)||'[]').filter(r=>r.runId!==runId);runs.push({runId,build:state.build,actor:'UNCLASSIFIED',qaVisible:qa,status:state.status,events:state.events});sessionStorage.setItem(key,JSON.stringify(runs.slice(-8)))}catch{}}
function suspend(reason){clear();pause(state,reason);audio.stop();persist();sync()}
function sync(){if(ui===state.status)return;ui=state.status;$('overlay').classList.toggle('won',ui==='won');$('overlay').classList.toggle('hidden',ui==='playing');$('pause').disabled=ui!=='playing';const f=state.fatal,dx=f?.sourceX-f?.x,dy=f?.sourceY-f?.y,origin=Number.isFinite(dx)&&Number.isFinite(dy)?((dx<-20?'左':dx>20?'右':'')+(dy<-20?'上':dy>20?'下':'' )||'近处')+'来袭':'';const names=['left','right'].filter(k=>state.p[k]).map(k=>k==='left'?'散射':'电炮');$('tag').textContent=ui==='won'?'RECLAIM':ui==='lost'?'RECLAIM':ui==='paused'?'战场已暂停':'夺走他们的火力';$('title').textContent=ui==='won'?'突围成功':ui==='lost'?'车辆损毁':ui==='paused'?'已暂停':'夺械突围';$('copy').innerHTML=ui==='won'?`${Math.round(state.t)} 秒 · 带出${names.join('、')||'原车'}${state.covers[1].alive?'<br>电炮仍在敌方':''}`:ui==='lost'?`${state.cause}${origin?` · ${origin}`:''}<br>${names.length?'丢失 '+names.join('、'):'未夺得敌方火力'}${state.exit?'<br>出口已打开':''}`:ui==='paused'?'准备好后继续。':'拖动闪避，趁过热夺炮。';$('action').textContent=ui==='paused'?'继续突围':ui==='lost'||ui==='won'?'再闯一次':'开始突围'}
$('action').onclick=()=>{if(!art)return;clear();audio.play('retry');if(state.status==='paused')resume(state);else{persist();state=create();wonAt=null;seen.clear();volley=0;runId=crypto.randomUUID();saved=0;start(state)}last=performance.now();sync();persist()};$('pause').onclick=()=>suspend('button');$('sound').onclick=()=>{const m=audio.toggle();$('sound').textContent=m?'声音 关':'声音 开';$('sound').setAttribute('aria-label',m?'开启声音':'关闭声音');if(!m)audio.play('contact')};
function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*390/r.width,y:(e.clientY-r.top)*760/r.height-(e.pointerType==='touch'?38:0)}}
canvas.onpointerdown=e=>{if(state.status!=='playing'||pointer!==null)return;e.preventDefault();pointer=e.pointerId;canvas.setPointerCapture(pointer);target=point(e);event(state,'input-start',{x:+state.p.x.toFixed(1),y:+state.p.y.toFixed(1),actor:'UNCLASSIFIED'})};canvas.onpointermove=e=>{if(e.pointerId===pointer)target=point(e)};canvas.onpointerup=e=>{if(e.pointerId===pointer)clear()};canvas.onpointercancel=e=>{if(e.pointerId===pointer){event(state,'input-cancel');clear()}};canvas.onlostpointercapture=e=>{if(e.pointerId===pointer)clear()};document.addEventListener('visibilitychange',()=>{if(document.hidden)suspend('hidden')});window.addEventListener('blur',()=>suspend('blur'));window.addEventListener('resize',()=>{if(state.status==='playing')suspend('resize');else clear()});
loadArt().then(a=>{art=a;$('action').disabled=false;sync()}).catch(e=>{$('error').classList.remove('hidden');$('error').textContent=e.message+'。请重新加载。';$('action').textContent='素材未就绪'});
function frame(now){const dt=(now-last)/1000;last=now;if(dt>.25&&state.status==='playing')suspend('long-frame');if(state.status==='playing'){acc+=Math.min(dt,.1);while(acc>=1/120){step(state,1/120,target);acc-=1/120}if(state.volley!==volley){volley=state.volley;audio.play(state.lastWeapon)}for(const e of state.events){if(seen.has(e))continue;seen.add(e);if(e.type==='hostile-fire'&&e.sourceId.startsWith('battery-'))audio.play(e.weapon);if(e.type==='capture')audio.play('dock');if(e.type==='capture-window')audio.play('contact');if(e.type==='reversal')audio.play('reversal');if(e.type==='pierce-chain')audio.play('pierce-chain');if(e.type==='destroy')audio.play('cut');if(e.type==='damage')audio.play('failure');if(e.type==='won')audio.play(state.p.right?'powered-exit':'restoration');if(e.type==='exit-open')audio.play('restoration')}persist()}if(state.status==='won'&&wonAt===null)wonAt=now;paint(ctx,state,art,target,wonAt===null?0:(now-wonAt)/1000);sync();if(qa&&now-qaAt>180){qaAt=now;$('qa').textContent=JSON.stringify({build:state.build,actor:'UNCLASSIFIED',status:state.status,t:+state.t.toFixed(3),p:state.p,kills:state.kills,reversal:state.reversal,fatal:state.fatal,exit:state.exit,covers:state.covers,enemyCount:state.enemies.length,enemies:state.enemies.map(e=>({id:e.id,x:e.x,y:e.y,r:e.r,entry:e.entry,attacks:e.attacks,hp:e.hp})),hostileShots:state.shots.filter(b=>b.enemy).map(b=>({x:b.x,y:b.y,vx:b.vx,vy:b.vy,r:b.r,sourceId:b.sourceId,weapon:b.kind})),events:state.events},null,2)}requestAnimationFrame(frame)}requestAnimationFrame(frame);

