export class Telemetry {
 constructor(candidate,build){const q=new URLSearchParams(location.search);this.candidate=candidate;this.build=build;this.qa=q.get('qa')==='1';this.stage=this.qa?'TECHNICAL_QA':q.get('novice')==='1'?'NOVICE_CHECK':'UNASSIGNED';this.session=crypto.randomUUID();this.rows=[];this.pending=[];this.seq=0;this.acked=0;this.newRun(false);this.timer=setInterval(()=>this.flush(),4000);document.addEventListener('visibilitychange',()=>{if(document.hidden){this.emit('visibility_exit','system',{visibility_only:true});this.flush();}});this.flush();}
 newRun(restart=true){this.run=crypto.randomUUID();this.start=performance.now();this.actionIndex=0;this.payoff=null;this.emit(restart?'restart':'session_start','system');}
 emit(name,actor='system',props={}){const id=crypto.randomUUID();const row={event:`studio_recovery001_${this.candidate}_${name}`,uuid:id,distinct_id:this.session,timestamp:new Date().toISOString(),properties:{...props,event_id:id,mission:'PUBLISHER_RECOVERY_001_GEN2',candidate:this.candidate,build:this.build,session_id:this.session,run_id:this.run,qa:this.qa,test_stage:this.stage,sequence:++this.seq,elapsed_ms:Math.round(performance.now()-this.start),actor,pull_eligible:false,unprompted_status:actor==='player'?'UNKNOWN_REQUIRES_OBSERVER':'NOT_PLAYER_ACTION',$process_person_profile:false,$geoip_disable:true,$ip:null}};this.rows.push(row);this.pending.push(row);return row;}
 action(name,props={}){this.actionIndex++;return this.emit(name,'player',{...props,action_index:this.actionIndex,first_action_ms:this.actionIndex===1?Math.round(performance.now()-this.start):null,after_payoff_ms:this.payoff===null?null:Math.round(performance.now()-this.payoff)});}
 reward(name,props={}){this.payoff=performance.now();this.emit(name,'automatic',props);this.flush();}
 async flush(){if(this.busy||!this.pending.length)return;const c=window.PROOF_ANALYTICS;if(!c?.host||!c?.token){this.delivery='local_only';return;}this.busy=true;try{while(this.pending.length){const batch=this.pending.slice(0,20),r=await fetch(c.host+'/batch/',{method:'POST',headers:{'Content-Type':'text/plain'},body:JSON.stringify({api_key:c.token,batch}),keepalive:true,signal:AbortSignal.timeout(8000)});if(!r.ok)throw Error('http');const a=await r.json();if(!(a===1||a==='1'||a?.status===1||String(a?.status).toLowerCase()==='ok'))throw Error('ack');this.pending.splice(0,batch.length);this.acked+=batch.length;}this.delivery='ingestion_acknowledged';}catch{this.delivery='retry_pending';}finally{this.busy=false;}}
 summary(state){return JSON.stringify({candidate:this.candidate,build:this.build,session:this.session,run:this.run,stage:this.stage,qa:this.qa,events:this.rows.length,acked:this.acked,pending:this.pending.length,delivery:this.delivery,state,novice:'NOT_ASSESSED'},null,2);}
 export(state){const u=URL.createObjectURL(new Blob([JSON.stringify({state,events:this.rows},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download=`recovery-${this.candidate}-${this.session}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
}
