import {BUILD,CROPS,GOALS,createGame,canPlace,cellsAt,fullLines,place,useTool,canAct,snapshot,random} from './engine.js';
import {Telemetry} from './telemetry.js';
const $=id=>document.getElementById(id),qa=new URLSearchParams(location.search).get('qa')==='1';
const names=['麦子','胡萝卜','鲜花'],facilityNames=['磨坊','水井','蜂屋'],toolNames=['小块种子','清出空地','蜜蜂采收'];
const art={wheat:'<path d="M17 30V9M17 16L9 9M17 22L9 16M17 27L9 23M17 16L25 9M17 22L25 16M17 27L25 23" stroke="#806024" stroke-width="2.5" stroke-linecap="round"/><path d="M15 12Q8 12 7 5Q14 4 15 12M19 12Q26 12 27 5Q20 4 19 12M15 19Q8 19 7 12Q14 11 15 19M19 19Q26 19 27 12Q20 11 19 19M15 26Q8 26 7 19Q14 18 15 26M19 26Q26 26 27 19Q20 18 19 26" fill="#fff0a4"/>',carrot:'<path d="M16 11Q22 9 24 15Q22 22 11 30Q10 18 16 11Z" fill="#ffce84"/><path d="M18 11Q13 1 17 3L20 9Q23 1 25 3L22 12M17 18L21 20M14 23L17 24" stroke="#548d50" stroke-width="3" stroke-linecap="round"/>',flower:'<path d="M17 18V31M17 27Q8 21 10 28L17 30" stroke="#4e7652" stroke-width="2.5"/><g fill="#ffe5e8"><ellipse cx="17" cy="9" rx="4" ry="6"/><ellipse cx="23" cy="14" rx="6" ry="4"/><ellipse cx="20" cy="20" rx="4" ry="6" transform="rotate(-35 20 20)"/><ellipse cx="12" cy="19" rx="4" ry="6" transform="rotate(35 12 19)"/><ellipse cx="10" cy="13" rx="6" ry="4"/></g><circle cx="17" cy="15" r="4" fill="#eeb65e"/>'};
function icon(c){return `<svg viewBox="0 0 34 34" class="crop-icon" aria-hidden="true">${art[c]}</svg>`;}
function facilitySVG(k){const shadow='<ellipse cx="62" cy="98" rx="43" ry="7" fill="#294e4425"/>';const mill='<path d="M40 43L84 43L91 96H33Z" fill="#f7e8bd"/><path d="M31 45L62 16L93 45Z" fill="#b97557"/><path d="M54 96V76Q62 65 70 76V96" fill="#6f6248"/><rect x="57" y="52" width="10" height="12" rx="4" fill="#f7c361"/><g class="sails" stroke="#6a7762" stroke-width="4"><path d="M62 8V74M29 40H95"/><path d="M60 9H51V31H60M72 42V51H94V42M64 71H73V49H64M52 38V29H30V38" fill="#fff4d0" stroke-width="1.5"/></g><circle cx="62" cy="40" r="5" fill="#806f48"/>';
const well='<path d="M37 58V90Q62 106 87 90V58" fill="#e5d7b0" stroke="#b5ac8d" stroke-width="2"/><ellipse cx="62" cy="59" rx="25" ry="9" fill="#698985"/><path d="M34 36V77M90 36V77" stroke="#806e48" stroke-width="6"/><path d="M23 39L62 13L100 39Z" fill="#79968a"/><path d="M25 38L62 21L99 38" fill="none" stroke="#aac3a1" stroke-width="3"/><path d="M36 67L85 67M39 80L85 80M50 65V78M70 80V94" stroke="#b1a686" stroke-width="2"/><path d="M64 38V64" stroke="#9d8b62" stroke-width="2"/><path d="M57 59H71L69 72H59Z" fill="#b38c56"/>';
const bees='<path d="M35 76H90V96H35Z" fill="#8c7350"/><path d="M40 73V41Q63 18 84 41V73Z" fill="#e8b96a"/><path d="M40 45H84M39 55H85M39 65H85" stroke="#b38a47" stroke-width="3"/><path d="M29 38L62 16L94 38Z" fill="#99706a"/><path d="M55 75V64Q62 54 69 64V75" fill="#735843"/><g fill="#f7d575"><ellipse cx="92" cy="53" rx="5" ry="3"/><ellipse cx="28" cy="65" rx="5" ry="3"/></g><g fill="#fff8dd"><ellipse cx="90" cy="48" rx="4" ry="3"/><ellipse cx="26" cy="60" rx="4" ry="3"/></g>';
return `<svg viewBox="0 0 124 108" aria-hidden="true">${shadow}<g class="building-shell">${[mill,well,bees][k]}</g></svg>`;}
const telemetry=new Telemetry(qa);let saved=null,storageOK=true;try{saved=JSON.parse(localStorage.getItem(qa?'harvest-home-qa-v1':'harvest-home-v1'));}catch{storageOK=false;}
let game=createGame(qa?29092026:Date.now(),saved),selection=0,activeTool=null,locked=false,offered=false,muted=true,ctx=null,toastTimer,drag=null;
if(saved?.board?.length===36&&saved.board.every(c=>c===null||CROPS.includes(c))&&saved.hand?.length===3&&saved.hand.every(p=>p===null||(CROPS.includes(p.crop)&&Array.isArray(p.cells)&&p.cells.length>0&&p.cells.length<=9&&p.cells.every(c=>Array.isArray(c)&&c.length===2&&c.every(n=>Number.isInteger(n)&&n>=0&&n<3))))){game.board=[...saved.board];game.hand=saved.hand;for(const key of ['progress','charge','tools'])if(saved[key]?.length===3&&saved[key].every(n=>Number.isInteger(n)&&n>=0&&n<=99))game[key]=[...saved[key]];game.total=Number(saved.total)||0;game.moves=Number(saved.moves)||0;game.season=Number(saved.currentSeason)||1;game.rng=random(game.seed+game.moves);selection=game.hand.findIndex(Boolean);offered=game.repaired.every(Boolean);telemetry.event('saved_home_resumed');}
function save(){try{localStorage.setItem(qa?'harvest-home-qa-v1':'harvest-home-v1',JSON.stringify({...snapshot(game),board:game.board,hand:game.hand,progress:game.progress,charge:game.charge,tools:game.tools,total:game.total,moves:game.moves,currentSeason:game.season}));}catch{storageOK=false;$('saveNote').textContent='浏览器未允许保存，本次仍可游玩';}}
function tone(freq=440,delay=0,duration=.16,volume=.045){if(muted||!ctx)return;try{const t=ctx.currentTime+delay,o=ctx.createOscillator(),g=ctx.createGain();o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(volume,t+.008);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g).connect(ctx.destination);o.start(t);o.stop(t+duration+.02);}catch{}}
function unlockAudio(){if(muted)return;try{ctx??=new(window.AudioContext||window.webkitAudioContext)();ctx.resume();}catch{}}
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),1700);}
function pieceMarkup(p){if(!p)return '<small>已种下</small>';const w=Math.max(...p.cells.map(c=>c[0]))+1,h=Math.max(...p.cells.map(c=>c[1]))+1;let s=`<div class="mini-grid" style="grid-template-columns:repeat(${w},17px)">`;for(let y=0;y<h;y++)for(let x=0;x<w;x++)s+=`<i class="mini-cell ${p.cells.some(c=>c[0]===x&&c[1]===y)?p.crop:'blank'}"></i>`;return s+'</div>';}
const cellEls=[];for(let i=0;i<36;i++){const b=document.createElement('button');b.className='cell';b.dataset.cell=i;b.addEventListener('click',()=>act(i));b.addEventListener('pointerenter',()=>preview(i));b.addEventListener('focus',()=>preview(i));$('board').append(b);cellEls.push(b);}
function render(){game.board.forEach((c,i)=>{const b=cellEls[i];b.className='cell '+(c?'crop-'+c:'empty');b.innerHTML=c?icon(c):'';b.setAttribute('aria-label',`${Math.floor(i/6)+1}行${i%6+1}列 ${c?names[CROPS.indexOf(c)]:'空地'}`);});
 $('facilities').innerHTML=facilityNames.map((n,k)=>`<div class="facility ${game.repaired[k]?'alive':''}" id="facility${k}">${facilitySVG(k)}<span class="house-name">${n}</span><div class="progress"><i style="width:${game.repaired[k]?100:Math.min(100,game.progress[k]/GOALS[k]*100)}%"></i></div><span class="demand">${game.repaired[k]?'已修好 · 正在运转':names[k]+' '+game.progress[k]+'/'+GOALS[k]}</span></div>`).join('');
 $('hand').innerHTML=game.hand.map((p,k)=>`<button class="seed ${selection===k&&activeTool===null?'selected':''}" data-slot="${k}" ${p?'':'disabled'} aria-label="${p?`${names[CROPS.indexOf(p.crop)]}种子 ${p.cells.length}格`:'已种下'}">${pieceMarkup(p)}${p?'<small>'+names[CROPS.indexOf(p.crop)]+'</small>':''}</button>`).join('');
 $('hand').querySelectorAll('.seed').forEach(b=>{b.addEventListener('click',()=>{if(locked)return;selection=+b.dataset.slot;activeTool=null;render();tone(330);});b.addEventListener('pointerdown',startDrag);});
 $('tools').innerHTML=toolNames.map((n,k)=>`<button class="tool ${game.tools[k]?'ready':''} ${activeTool===k?'selected':''}" data-tool="${k}" ${game.tools[k]?'':'disabled'} aria-label="${n} ${game.tools[k]?'可用':game.repaired[k]?'充能中':'待修复'}"><span class="tool-glyph">${['✂','◈','✿'][k]}</span><span>${n}<small>${game.tools[k]?'已就绪':game.repaired[k]?names[k]+' '+game.charge[k]+'/6':facilityNames[k]+'待修复'}</small></span></button>`).join('');
 $('tools').querySelectorAll('button').forEach(b=>b.onclick=()=>{if(locked)return;unlockAudio();const k=+b.dataset.tool;if(k===0){attemptTool(k);return;}activeTool=k;render();});
 $('harvestCount').textContent=game.total;$('season').textContent='第 '+game.season+' 季';$('homeGoal').textContent='让小院重新运转 · '+game.repaired.filter(Boolean).length+'/3';$('instruction').textContent=activeTool===1?'点一片田地，清出 2×2 空间':activeTool===2?'点一种作物，蜜蜂收走所有同种作物':'选一块种子，点空地种下 · 满行或满列就收获';$('cancel').hidden=activeTool===null;$('goal').textContent=game.repaired.every(Boolean)?'小院在帮你，试试新的收获':'种满一行，收获好日子';qaOutput();}
function clearPreview(){cellEls.forEach(b=>b.classList.remove('preview','invalid','will-clear','tool-target'));}
function preview(i){clearPreview();if(locked)return;if(activeTool!==null){if(activeTool===1){const x=Math.min(4,i%6),y=Math.min(4,Math.floor(i/6));[y*6+x,y*6+x+1,(y+1)*6+x,(y+1)*6+x+1].forEach(n=>cellEls[n].classList.add('tool-target'));}else game.board.forEach((c,n)=>{if(c&&c===game.board[i])cellEls[n].classList.add('tool-target');});return;}
 const p=game.hand[selection];if(!p)return;const ok=canPlace(game,p,i%6,Math.floor(i/6)),copy=[...game.board];cellsAt(p,i%6,Math.floor(i/6)).forEach(([x,y])=>{if(x<6&&y<6&&x>=0&&y>=0){cellEls[y*6+x].classList.add(ok?'preview':'invalid');if(ok)copy[y*6+x]=p.crop;}});if(ok)fullLines(copy).indices.forEach(n=>cellEls[n].classList.add('will-clear'));}
function particles(out){for(const {i,crop} of out.cleared){const a=cellEls[i].getBoundingClientRect(),b=$('facility'+CROPS.indexOf(crop)).getBoundingClientRect(),e=document.createElement('div');e.className='particle';e.innerHTML=icon(crop);e.style.left=a.left+a.width/2-12+'px';e.style.top=a.top+a.height/2-12+'px';e.style.setProperty('--dx',b.left+b.width/2-a.left-a.width/2+'px');e.style.setProperty('--dy',b.top+b.height/2-a.top-a.height/2+'px');$('particles').append(e);setTimeout(()=>e.remove(),750);}}
function confetti(){const b=$('homestead')?.getBoundingClientRect()||$('facilities').getBoundingClientRect();for(let j=0;j<24;j++){const s=document.createElement('i');s.className='spark';s.style.left=b.left+b.width/2+'px';s.style.top=b.top+45+'px';s.style.background=['#edbc59','#f5e6bb','#84a879','#c789a1'][j%4];s.style.setProperty('--dx',(Math.random()-.5)*280+'px');s.style.setProperty('--dy',(Math.random()-.5)*220+'px');$('particles').append(s);setTimeout(()=>s.remove(),900);}}
function feedback(out,kind){telemetry.action(kind);if(out.cleared.length){particles(out);tone(523,0);tone(659,.07);tone(784,.15);telemetry.event('harvest',{crops:out.counts,count:out.cleared.length,tool:kind!=='place'});if(!telemetry.payoff){telemetry.payoff=true;telemetry.event('first_payoff');}toast(out.repairs.length?`${facilityNames[out.repairs[0]]}修好了 · 新工具已就绪`:`收获 ${out.cleared.length} 份 · 空间腾出来了`);$('board').classList.remove('pulse');requestAnimationFrame(()=>$('board').classList.add('pulse'));}else tone(293.66);
 for(const k of out.repairs){telemetry.event('facility_repaired',{facility:k});setTimeout(()=>{confetti();tone(523,0,.3);tone(659,.1,.3);tone(1046,.2,.4);},350);}out.charged.forEach(k=>telemetry.event('tool_recharged',{tool:k}));save();selection=game.hand[selection]?selection:game.hand.findIndex(Boolean);render();out.planted?.forEach(i=>cellEls[i].classList.add('just-planted'));
 if(game.repaired.every(Boolean)&&!offered){offered=true;setTimeout(()=>showResult(true),1250);}else if(!canAct(game)){game.ended=true;setTimeout(()=>showResult(false),900);}telemetry.flush();}
function act(i){if(locked||game.ended)return;unlockAudio();if(activeTool!==null){attemptTool(activeTool,i);return;}if(!game.hand[selection])return;telemetry.event('input_attempt',{kind:'place'});const out=place(game,selection,i%6,Math.floor(i/6));if(!out.ok){telemetry.event('input_error',{reason:out.reason});preview(i);toast('这里放不下，换块空地试试');tone(150,0,.09,.02);return;}feedback(out,'place');}
function attemptTool(k,i){telemetry.event('input_attempt',{kind:'tool',tool:k});const out=useTool(game,k,i);if(!out.ok){telemetry.event('input_error',{reason:out.reason});toast(out.reason==='already_small'?'这些种子已经很小，留到下一组用吧':'这片没有可收获的作物');return;}activeTool=null;telemetry.event('tool_used',{tool:k});if(k===0)toast('磨坊帮你把大块种子变小了');feedback(out,'tool_'+k);}
function startDrag(e){if(locked||!game.hand[+e.currentTarget.dataset.slot])return;drag={id:e.pointerId,slot:+e.currentTarget.dataset.slot,x:e.clientX,y:e.clientY,moved:false,target:null};e.currentTarget.setPointerCapture(e.pointerId);}
window.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;const d=drag;if(!d.moved&&Math.hypot(e.clientX-d.x,e.clientY-d.y)<9)return;d.moved=true;selection=d.slot;activeTool=null;const first=cellEls[0].getBoundingClientRect(),stride=cellEls[1].getBoundingClientRect().left-first.left,gap=stride-first.width,py=e.pointerType==='touch'?e.clientY-first.width*.9:e.clientY,x=Math.floor((e.clientX-first.left+gap/2)/stride),y=Math.floor((py-first.top+gap/2)/stride);d.target=x>=0&&x<6&&y>=0&&y<6?y*6+x:null;const ghost=$('dragGhost');ghost.innerHTML=pieceMarkup(game.hand[d.slot]);ghost.style.display='block';ghost.style.left=e.clientX-19+'px';ghost.style.top=py-19+'px';if(d.target!==null)preview(d.target);else clearPreview();},{passive:true});
window.addEventListener('pointerup',e=>{if(!drag||drag.id!==e.pointerId)return;const d=drag;drag=null;$('dragGhost').style.display='none';if(d.moved){e.preventDefault();if(d.target!==null)act(d.target);else{telemetry.event('drag_cancelled');clearPreview();}}});
window.addEventListener('pointercancel',()=>{drag=null;$('dragGhost').style.display='none';clearPreview();});
$('board').addEventListener('pointerleave',()=>{if(!drag)clearPreview();});$('cancel').onclick=()=>{activeTool=null;render();};
function showResult(success){if($('result').open)return;$('resultKicker').textContent=success?'A PLACE OF YOUR OWN':'A LITTLE REST';$('resultTitle').textContent=success?'小院，真的活起来了':'这一季，先收工吧';$('resultArt').textContent=success?'✦':'❋';$('resultText').textContent=success?'磨坊转了，井水回来了，蜜蜂也住下了。下一季，带着修好的工具再种一片。':'这片田地暂时放不下了。已经修好的小院会留下，下一季可以重新安排。';$('stay').textContent=success?'继续种这片田':'看看我的小院';$('result').showModal();telemetry.event(success?'season_restored':'board_stalled');}
function newRun(){const home=snapshot(game);telemetry.newRun();game=createGame(Date.now(),home);selection=0;activeTool=null;offered=game.repaired.every(Boolean);locked=false;save();render();toast('新一季，带着自己的小院出发');telemetry.flush();}
$('continue').onclick=()=>{$('result').close();newRun();};$('stay').onclick=()=>$('result').close();$('newRun').onclick=newRun;$('help').onclick=()=>{$('info').showModal();telemetry.event('help_opened');};document.querySelectorAll('dialog .close').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('sound').onclick=()=>{muted=!muted;unlockAudio();$('sound').classList.toggle('on',!muted);$('sound').setAttribute('aria-label',muted?'开启声音':'关闭声音');tone(523,0,.25);telemetry.event('sound_changed',{enabled:!muted,audio_state:ctx?.state||'unavailable'});};
function qaOutput(){if(!qa)return;$('qa').hidden=false;$('qaOutput').textContent=JSON.stringify({build:BUILD,session:telemetry.session,run:telemetry.run,moves:game.moves,actions:telemetry.actions,harvest:game.total,repaired:game.repaired,tools:game.tools,events:telemetry.rows.length,acked:telemetry.acked,pending:telemetry.pending.length,status:telemetry.status,error:telemetry.lastError,audio:ctx?.state||'off'});}
telemetry.onchange=qaOutput;$('telemetry').onclick=()=>{$('recordsText').textContent=`本次事件 ${telemetry.rows.length} 条\n接收端已确认 ${telemetry.acked} 条\n待重试 ${telemetry.pending.length} 条\n状态 ${telemetry.status}\n匿名会话 ${telemetry.session}\n${qa?'此会话为自动化 QA，不属于真人测试。':'点击顺序不代表有趣，也不能自动证明无人指导。'}`;$('records').showModal();telemetry.flush();};
$('export').onclick=()=>{const blob=new Blob([JSON.stringify({build:BUILD,qa,session:telemetry.session,rows:telemetry.rows},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='harvest-session-'+telemetry.session+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden'){save();telemetry.leaving();}else telemetry.event('page_returned');});window.addEventListener('pagehide',save);setInterval(()=>telemetry.flush(),5000);window.addEventListener('error',()=>telemetry.event('runtime_error'));window.addEventListener('unhandledrejection',()=>telemetry.event('runtime_rejection'));
render();if(!storageOK)$('saveNote').textContent='浏览器未允许保存，本次仍可游玩';if(!canAct(game)){game.ended=true;showResult(false);}telemetry.flush();


