export const anchors=Array.from({length:6},(_,i)=>({x:100+i*38,y:610}));
export function create(){return{time:0,balls:anchors.map((a,i)=>({id:i,slot:i,x:a.x,y:510,vx:0,vy:0,r:15,phase:i*.7+.15,tether:true,parked:false})),panels:Array.from({length:8},(_,i)=>({id:i,x:33+(i%4)*82,y:i<4?292:210,w:78,h:74,intact:true})),events:[],cuts:0,hits:0};}
export function pose(b,time){const t=time*4.6+b.phase,a=.95*Math.sin(t),av=.95*4.6*Math.cos(t),p=anchors[b.slot];return{x:p.x+Math.sin(a)*65,y:p.y-Math.cos(a)*205,vx:Math.cos(a)*65*av,vy:Math.sin(a)*205*av};}
export function cut(s,id){const b=s.balls.find(b=>b.id===id);if(!b?.tether)return false;Object.assign(b,pose(b,s.time));b.tether=false;b.parked=false;s.cuts++;s.events.push({type:'cut',id,x:b.x,y:b.y,vx:b.vx,vy:b.vy});return true;}
export function rehang(s,id,slot){const b=s.balls.find(b=>b.id===id);if(!b?.parked||slot<0||slot>=6||s.balls.some(v=>v.tether&&v.slot===slot))return false;b.slot=slot;b.phase=slot*.7+.15;b.tether=true;b.parked=false;Object.assign(b,pose(b,s.time));s.events.push({type:'rehang',id,slot});return true;}
function collision(a,b){if(a.parked||b.parked)return;const dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy),r=a.r+b.r;if(d>=r||d<.0001)return;const nx=dx/d,ny=dy/d,invA=a.tether||a.parked?0:1,invB=b.tether||b.parked?0:1,sum=invA+invB;if(!sum)return;const overlap=r-d;a.x-=nx*overlap*invA/sum;a.y-=ny*overlap*invA/sum;b.x+=nx*overlap*invB/sum;b.y+=ny*overlap*invB/sum;const avx=invA?a.vx:0,avy=invA?a.vy:0,bvx=invB?b.vx:0,bvy=invB?b.vy:0;const v=(bvx-avx)*nx+(bvy-avy)*ny;if(v<0){const j=-1.55*v/sum;a.vx-=j*nx*invA;a.vy-=j*ny*invA;b.vx+=j*nx*invB;b.vy+=j*ny*invB;}}
export function step(s,dt){s.time+=dt;for(const b of s.balls){if(b.tether){Object.assign(b,pose(b,s.time));continue;}if(b.parked)continue;b.vy+=180*dt;b.x+=b.vx*dt;b.y+=b.vy*dt;if(b.x<b.r+23){b.x=b.r+23;b.vx=Math.abs(b.vx)*.82;}if(b.x>367-b.r){b.x=367-b.r;b.vx=-Math.abs(b.vx)*.82;}if(b.y<132+b.r){b.y=132+b.r;b.vy=Math.abs(b.vy)*.8;}for(const p of s.panels){if(!p.intact)continue;const qx=Math.max(p.x,Math.min(b.x,p.x+p.w)),qy=Math.max(p.y,Math.min(b.y,p.y+p.h));let dx=b.x-qx,dy=b.y-qy,d=Math.hypot(dx,dy);if(d>b.r)continue;if(d<.00001){const faces=[[b.x-p.x,-1,0],[p.x+p.w-b.x,1,0],[b.y-p.y,0,-1],[p.y+p.h-b.y,0,1]].sort((a,b)=>a[0]-b[0]);dx=faces[0][1];dy=faces[0][2];d=1;}const nx=dx/d,ny=dy/d,vn=b.vx*nx+b.vy*ny;if(vn>=0)continue;const speed=Math.hypot(b.vx,b.vy);if(-vn>115){const after=-Math.sqrt(Math.max(0,vn*vn-115*115));b.vx+=(after-vn)*nx;b.vy+=(after-vn)*ny;p.intact=false;s.hits++;s.events.push({type:'fracture',panel:p.id,ball:b.id,x:qx,y:qy,speed,normal:[nx,ny],normalBefore:vn,normalAfter:after});}else{b.x+=nx*(b.r-d+.01);b.y+=ny*(b.r-d+.01);b.vx-=1.32*vn*nx;b.vy-=1.32*vn*ny;}}if(b.y>=650){b.y=650+(b.id%2)*6;b.x=Math.max(44,Math.min(346,b.x));b.vx=0;b.vy=0;b.parked=true;s.events.push({type:'parked',id:b.id});}}
 for(let i=0;i<s.balls.length;i++)for(let j=i+1;j<s.balls.length;j++)collision(s.balls[i],s.balls[j]);}
export function drain(s){return s.events.splice(0);}
export function intersect(a,b,c,d){const cr=(p,q,r)=>(q.x-p.x)*(r.y-p.y)-(q.y-p.y)*(r.x-p.x);return cr(a,b,c)*cr(a,b,d)<=0&&cr(c,d,a)*cr(c,d,b)<=0&&Math.max(a.x,b.x)>=Math.min(c.x,d.x)&&Math.min(a.x,b.x)<=Math.max(c.x,d.x)&&Math.max(a.y,b.y)>=Math.min(c.y,d.y)&&Math.min(a.y,b.y)<=Math.max(c.y,d.y);}
