import{BUILD,initial,available,cut,preview,pick,summary,TIPS}from'./engine.mjs';
import{loadArt}from'./assets.js';import{createPainter,fruitPoints}from'./paint.js';import{createAudio}from'./audio.js';
const canvas=document.querySelector('canvas'),c=canvas.getContext('2d'),params=new URLSearchParams(location.search),qa=params.get('qa')==='1',STORE='crystal-branch-run-v1';canvas.width=780;canvas.height=1560;c.scale(2,2);
const audio=createAudio();let state=initial(),events=[],epoch=performance.now(),run=1,time=0,last=epoch,activePointer=null,origin=null,selected=null,path=[],transition=null,painter=null,ready=false,resumed=false,resumeNoticeUntil=0;
const log=(event,data={})=>{events.push({run,event,ms:+(performance.now()-epoch).toFixed(1),activeMs:+(time*1000).toFixed(1),...data});if(events.length>350)events.shift()};
function sound(kind){const data=audio.play(kind);if(data)log('AUDIO_SCHEDULED',data)}
function persist(){try{localStorage.setItem(STORE,JSON.stringify({build:BUILD,state,time,events,run}))}catch{log('SAVE_UNAVAILABLE')}}
function clearPointer(reason){if(activePointer!==null)log('INPUT_CANCEL',{reason,pointer:activePointer});activePointer=null;origin=null;selected=null;path=[]}
function reset(same=false){log('RETRY',{sameSeed:same,previous:summary(state)});audio.stop();clearPointer('retry');state=initial(same?state.seed:state.seed+1);time=0;epoch=last=performance.now();run++;transition=null;resumed=false;log('GAME_START',{build:BUILD,state:summary(state)});persist();sound('retry')}
function commit(id){resumed=false;const before=structuredClone(state),result=cut(state,id);if(!result)return;let drop=result.effect.ids.flatMap(i=>fruitPoints(before,i));state=result.state;transition={start:time,before,effect:result.effect,drop,collected:false,converged:false,bloomed:false};log('ACTION',{number:state.cuts,branch:id,before:summary(before),after:summary(state),effect:result.effect});if(state.cuts===1)log('FIRST_ACTION');if(state.cuts===5)log('ACTION_5');if(state.cuts===10)log('ACTION_10');log('MICRO_PAYOFF',{kind:'branch_cut',fruit:drop.length});if(state.cuts===1)log('FIRST_PAYOFF');sound('cut');persist()}
const point=e=>{const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*390/r.width,y:(e.clientY-r.top)*780/r.height}};
canvas.onpointerdown=e=>{if(!ready||state.status!=='playing'||transition)return;if(activePointer!==null){log('FOREIGN_POINTER_IGNORED',{id:e.pointerId,phase:'down'});return}activePointer=e.pointerId;canvas.setPointerCapture(e.pointerId);origin=point(e);path=[origin];selected=null;log('POINTER_DOWN',{id:e.pointerId,...origin})};
canvas.onpointermove=e=>{if(activePointer===null)return;if(e.pointerId!==activePointer){log('FOREIGN_POINTER_IGNORED',{id:e.pointerId,phase:'move'});return}const p=point(e);path.push(p);if(path.length>24)path.shift();const id=pick(state,origin,p);if(id!==selected){selected=id;if(id!==null){sound('contact');log('PREVIEW',{branch:id,effect:preview(state,id)})}}};
canvas.onpointerup=e=>{if(activePointer===null||e.pointerId!==activePointer)return;const p=point(e),id=pick(state,origin,p);activePointer=null;origin=null;selected=null;path=[];if(id!==null)commit(id);else log('EMPTY_SWIPE')};
canvas.onpointercancel=e=>{if(e.pointerId===activePointer)clearPointer('pointercancel')};canvas.onlostpointercapture=e=>{if(e.pointerId===activePointer)clearPointer('lostcapture')};
document.addEventListener('visibilitychange',()=>{last=performance.now();if(document.hidden){clearPointer('hidden');audio.stop();persist();log('BACKGROUND_PAUSE')}else log('FOREGROUND_RESUME')});window.addEventListener('resize',()=>{clearPointer('resize');log('RESIZE',{width:innerWidth,height:innerHeight})});window.addEventListener('pagehide',()=>{clearPointer('pagehide');log('SESSION_END',{state:summary(state)});persist()});
document.querySelector('#same-play').onclick=()=>reset(true);document.querySelector('#retry').onclick=()=>reset(false);document.querySelector('#sound').onclick=e=>{e.target.textContent=audio.toggle()?'声音 关':'声音 开';log('MUTE',{muted:audio.muted})};if(qa)document.querySelector('#qa').style.display='inline-block';
function inspect(){document.querySelector('pre').textContent=JSON.stringify({build:BUILD,classification:'Local event log; CPU timing, not photon or audible latency',state:summary(state),events},null,2);document.querySelector('dialog').showModal()}
document.querySelector('#qa').onclick=inspect;document.querySelector('#close').onclick=()=>document.querySelector('dialog').close();document.querySelector('#same').onclick=()=>{document.querySelector('dialog').close();reset(true)};document.querySelector('#export').onclick=()=>{const a=document.createElement('a'),u=URL.createObjectURL(new Blob([document.querySelector('pre').textContent],{type:'application/json'}));a.href=u;a.download='crystal-branch-qa.json';a.click();URL.revokeObjectURL(u)};
function frame(now){let dt=(now-last)/1000;last=now;if(document.hidden){requestAnimationFrame(frame);return}if(dt>.25){log('LONG_STALL_PAUSE',{ms:dt*1000});dt=0}time+=dt;if(transition){const q=time-transition.start;if(q>.22&&!transition.collected){transition.collected=true;sound('collection');log('COLLECTION',{count:transition.drop.length})}if(q>.38&&!transition.converged){transition.converged=true;if(transition.effect.groups){sound('convergence');log('MEDIUM_PAYOFF',{groups:transition.effect.groups,slotsFreed:transition.effect.groups*3})}}if(q>.53&&!transition.bloomed){transition.bloomed=true;if(transition.effect.flowersAfter>transition.effect.flowersBefore){sound('restoration');log('FLOWER_RESTORED',{flowers:transition.effect.flowersAfter});if(transition.effect.groups>=2)log('MAJOR_PAYOFF',{groups:transition.effect.groups,flowers:transition.effect.flowersAfter})}}if(q>.78){transition=null;if(state.status!=='playing'){log(state.status==='won'?'WIN':'FAIL',{reason:state.reason,state:summary(state)});if(state.status==='failed')sound('failure');persist()}}}painter.draw({state,time,selected,pointer:activePointer,path,transition,resumed:resumed&&now<resumeNoticeUntil});requestAnimationFrame(frame)}
loadArt().then(art=>{painter=createPainter(c,art);try{const saved=JSON.parse(localStorage.getItem(STORE));if(saved?.build===BUILD&&saved.state?.status==='playing'&&Number.isInteger(saved.state.removed)&&saved.state.removed>=0&&saved.state.removed<4096&&saved.state.tray?.length===4&&saved.state.tray.every(n=>Number.isInteger(n)&&n>=0&&n<=2)&&saved.state.cuts<12){state=saved.state;time=saved.time||0;events=saved.events||[];run=saved.run||1;resumed=true;resumeNoticeUntil=performance.now()+12000}}catch{}ready=true;epoch=last=performance.now();document.querySelector('#loading').hidden=true;for(const id of ['same-play','retry','sound'])document.querySelector('#'+id).disabled=false;log(resumed?'RETURN':'GAME_START',{build:BUILD,assets:art.status,failed:art.failed,state:summary(state)});requestAnimationFrame(frame)});
