const mode=[1,2,3].includes(Number(new URLSearchParams(location.search).get('loop')))?Number(new URLSearchParams(location.search).get('loop')):1;
const BUILD='continuous-gen3-0.3.0',canvas=document.querySelector('canvas'),c=canvas.getContext('2d');canvas.width=780;canvas.height=1560;c.scale(2,2);
const palette=['#65efd3','#ffbd80','#c2a5ff'],accent=palette[mode-1];let audio;try{audio=new AudioContext()}catch{}const voices=new Set();let muted=false,events=[],run=0,epoch=performance.now(),last=epoch,t=0,gesture=0,inputNo=0,score=0,streak=0,best=0,successes=0,down=false,prev=null,origin=null,grab=null,counted=false,hitThis=false,bodies=[],shots=[],fx=[],rings=[],labels=[],trail=[],pending=[],shake=0,flare=0,stage=0,need=1,corePulse=0,wave=0,chainQueue=[],links=[],needsRefresh=false,missFlash=0,pieces=[],fusions=[],chains=new Map(),chainId=0;
function log(event,data={}){events.push({run,event,ms:+(performance.now()-epoch).toFixed(2),...data})}
function sound(kind){if(muted||!audio)return;audio.resume();let now=audio.currentTime,base={action:mode===1?680:240,impact:mode===2?105:mode===3?420:520,combo:540,escalation:720,miss:110,reset:180}[kind],notes=kind==='escalation'?[1,1.25,1.5,2]:kind==='combo'?[1,1.5]:[1,.5];for(let i=0;i<notes.length;i++){let o=audio.createOscillator(),g=audio.createGain(),at=now+i*.025;o.type=kind==='impact'?'triangle':'sine';o.frequency.setValueAtTime(base*notes[i]*(1+Math.min(streak,10)*.025),at);o.frequency.exponentialRampToValueAtTime(base*notes[i]*.6,at+.18);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(.07/(i+1),at+.004);g.gain.exponentialRampToValueAtTime(.0001,at+.23);o.connect(g).connect(audio.destination);let v={o,g};voices.add(v);o.onended=()=>{voices.delete(v);o.disconnect();g.disconnect()};o.start(at);o.stop(at+.3)}if(kind==='action'||kind==='impact'){let len=Math.floor(audio.sampleRate*.07),buffer=audio.createBuffer(1,len,audio.sampleRate),samples=buffer.getChannelData(0);for(let i=0;i<len;i++)samples[i]=(Math.random()*2-1)*(1-i/len);let o=audio.createBufferSource(),g=audio.createGain(),filter=audio.createBiquadFilter();o.buffer=buffer;filter.type='bandpass';filter.frequency.value=mode===1?2400:mode===2?420:1200;filter.Q.value=.7;g.gain.setValueAtTime(kind==='impact'?.065:.025,now);g.gain.exponentialRampToValueAtTime(.0001,now+.07);o.connect(filter).connect(g).connect(audio.destination);let v={o,g};voices.add(v);o.onended=()=>{voices.delete(v);o.disconnect();filter.disconnect();g.disconnect()};o.start(now);o.stop(now+.08)}log('audio_scheduled',{kind,layers:(kind==='action'||kind==='impact')?'tonal+filtered_transient':'pitched_sequence',audio_time:now,state:audio.state,audible_onset:'UNKNOWN'})}
function stopAudio(){let n=voices.size;for(let v of voices){v.g.gain.cancelScheduledValues(0);v.g.disconnect();try{v.o.stop()}catch{}}voices.clear();log('audio_stopped',{count:n})}
function input(kind){if(counted)return;counted=true;inputNo++;log('meaningful_input',{number:inputNo,gesture,kind});if(inputNo===1)log('first_input');sound('action')}
function opportunity(reason){log('opportunity_ready',{reason,for_input:inputNo+1})}
function spawnCut(slot,delay=0){let phase=(successes*1.13+slot*1.7);bodies.push({slot,x:[85,195,305][slot],y:310+((successes+slot)%3)*48,baseX:[85,195,305][slot],baseY:310+((successes+slot)%3)*48,r:30,a:slot*.3,born:t+delay,phase,eligible:gesture+1,type:'facet'})}
const formations=[{p:[[80,270],[185,340],[285,255],[300,450]],e:[[0,1],[1,2]]},{p:[[80,345],[185,245],[300,330],[190,440]],e:[[0,1],[2,3]]},{p:[[85,290],[205,235],[305,360],[170,440]],e:[[0,3],[3,2]]}];
function refreshTargets(){let f=formations[wave%3];links=f.e;for(let slot=0;slot<4;slot++){let [x,y]=f.p[slot],old=bodies.find(b=>b.slot===slot);if(old){old.tx=x;old.ty=y;old.charged=false}else bodies.push({slot,x,y,tx:x,ty:y,r:27,type:'target',born:t})}log('formation',{wave,positions:f.p,links:f.e});opportunity('formation_live')}
function triggerChain(hit,s){let id=++chainId,ordinal=0;let queue=[{b:hit,at:t,from:null}],seen=new Set([hit.slot]);while(queue.length){let item=queue.shift();item.b.charged=true;chainQueue.push({...item,id,ordinal:++ordinal,vx:s.vx,vy:s.vy,input:s.input,gesture:s.gesture,start:item.from?item.at-Math.hypot(item.b.x-item.from.x,item.b.y-item.from.y)/600:item.at});for(let edge of links){let other=edge[0]===item.b.slot?edge[1]:edge[1]===item.b.slot?edge[0]:null;if(other===null||seen.has(other))continue;let b=bodies.find(b=>b.slot===other&&!b.charged);if(b){seen.add(other);queue.push({b,at:item.at+Math.hypot(b.x-item.b.x,b.y-item.b.y)/600,from:{x:item.b.x,y:item.b.y}})}}}chains.set(id,{left:seen.size,total:seen.size,input:s.input});s.hits=seen.size;s.age=3;needsRefresh=true;log('chain_started',{input:s.input,count:seen.size})}
function satellites(){const arrangements=[[[75,475],[195,555],[315,465]],[[95,530],[305,510],[195,430]],[[310,460],[80,470],[205,555]],[[195,540],[310,475],[80,460]]];let p=arrangements[successes%4],values=[1,2,3];let shift=(Math.floor(successes/2)+successes)%3; bodies=p.map(([x,y],i)=>({x,y,homeX:x,homeY:y,r:29,value:values[(i+shift)%3],type:'seed',returning:false}));log('matching_layout',{successes,need,positions:bodies.map(b=>({x:b.x,y:b.y,value:b.value}))})}
function reset(){stopAudio();run++;epoch=performance.now();last=epoch;t=0;inputNo=0;score=0;streak=0;successes=0;stage=0;need=1;down=false;prev=null;grab=null;counted=false;shots=[];bodies=[];fx=[];rings=[];labels=[];trail=[];pending=[];shake=0;flare=0;corePulse=0,wave=0,chainQueue=[],links=[],needsRefresh=false,missFlash=0;pieces=[];fusions=[];chains.clear();chainId=0;gesture=0;if(mode===1)for(let i=0;i<3;i++)spawnCut(i);if(mode===2)refreshTargets();if(mode===3)satellites();log('run_ready',{build:BUILD,loop:mode});pending.push({kind:'ready',at:performance.now()});opportunity('initial');sound('reset')}
function burst(x,y,big=false){for(let i=0;i<(big?55:22);i++){let a=Math.random()*Math.PI*2,s=60+Math.random()*(big?340:180);fx.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,age:0,life:.24+Math.random()*.35,r:1+Math.random()*3})}rings.push({x,y,age:0,big});shake=big?7:3;flare=big?.1:.025;pending.push({kind:'impact',at:performance.now()})}
function payoff(x,y,amount=1){successes++;streak++;best=Math.max(best,streak);let add=10*amount*(1+Math.floor(streak/5));score+=add;burst(x,y);labels.push({x,y,age:0,text:'+'+add});log('payoff',{input:inputNo,gesture,score,streak,successes});if(successes===1)log('first_payoff');sound('impact');if(streak%3===0){sound('combo');log('combo',{streak})}if(successes%5===0){stage++;burst(195,350,true);labels.push({x:195,y:215,age:0,text:'共鸣 '+stage});sound('escalation');log('escalation',{stage,successes})}}
function miss(reason){let lost=streak;streak=0;score=Math.max(0,score-10);missFlash=.22;sound('miss');log('miss',{input:inputNo,reason,lost_streak:lost,score});labels.push({x:195,y:420,age:0,text:mode===3?'纹路不同 · −10':'连击中断 · −10'});opportunity('miss_recoverable')}
function facetHit(b,a,z){let ca=Math.cos(b.a),sa=Math.sin(b.a),local=p=>({x:(p.x-b.x)*ca+(p.y-b.y)*sa,y:-(p.x-b.x)*sa+(p.y-b.y)*ca}),p=local(a),q=local(z),lo=0,hi=1;for(let [nx,ny]of[[1,1],[1,-1],[-1,1],[-1,-1]]){let v=nx*p.x+ny*p.y,d=nx*(q.x-p.x)+ny*(q.y-p.y);if(Math.abs(d)<1e-9){if(v>b.r)return false}else{let e=(b.r-v)/d;if(d>0)hi=Math.min(hi,e);else lo=Math.max(lo,e);if(lo>hi)return false}}return true}

// Physical silhouettes remain separate from non-blocking score and opportunity state.
function polygon(points){c.beginPath();points.forEach((p,i)=>i?c.lineTo(p[0],p[1]):c.moveTo(p[0],p[1]));c.closePath()}
function clipHalf(points,a,z,sign){let out=[],side=p=>sign*((z.x-a.x)*(p[1]-a.y)-(z.y-a.y)*(p[0]-a.x));for(let i=0;i<points.length;i++){let p=points[i],q=points[(i+1)%points.length],u=side(p),v=side(q);if(u>=0)out.push(p);if((u>=0)!==(v>=0)){let f=u/(u-v);out.push([p[0]+(q[0]-p[0])*f,p[1]+(q[1]-p[1])*f])}}return out}
function splitFacet(b,a,z){let verts=[[0,-b.r],[b.r,0],[0,b.r],[-b.r,0]].map(([x,y])=>[b.x+x*Math.cos(b.a)-y*Math.sin(b.a),b.y+x*Math.sin(b.a)+y*Math.cos(b.a)]),dx=z.x-a.x,dy=z.y-a.y,d=Math.hypot(dx,dy),speed=Math.min(240,90+d*3);for(let sign of[-1,1]){let points=clipHalf(verts,a,z,sign);if(points.length<3)continue;pieces.push({x:b.x,y:b.y,points:points.map(([x,y])=>[x-b.x,y-b.y]),vx:-dy/d*sign*speed+dx/d*65,vy:dx/d*sign*speed+dy/d*65-35,age:0,life:.48,rot:0,spin:sign*2.6,color:sign>0?'#aaffec':'#37b99f',kind:'cut'})}log('facet_split',{input:inputNo,parts:2,line:[a.x,a.y,z.x,z.y],direction:[dx/d,dy/d]})}
function fracture(item){let b=item.b,n=5+Math.min(item.ordinal,3),angle=item.from?Math.atan2(b.y-item.from.y,b.x-item.from.x):Math.atan2(item.vy,item.vx);for(let i=0;i<n;i++){let a=i/n*Math.PI*2,q=(i+1)/n*Math.PI*2,mid=(a+q)/2;pieces.push({x:b.x,y:b.y,points:[[0,0],[Math.cos(a)*b.r,Math.sin(a)*b.r],[Math.cos(q)*b.r,Math.sin(q)*b.r]],vx:Math.cos(mid)*(90+item.ordinal*32)+Math.cos(angle)*100,vy:Math.sin(mid)*(90+item.ordinal*32)+Math.sin(angle)*100,age:0,life:.42+item.ordinal*.04,rot:0,spin:(i%2?1:-1)*(2+item.ordinal),color:['#ffdcad','#dc8c55','#fff6dc'][i%3],kind:'impact'})}labels.push({x:b.x,y:b.y-35,age:0,text:'破裂 '+item.ordinal});log('fracture',{input:item.input,ordinal:item.ordinal,pieces:n,direction:angle})}
function drawPieces(){for(let p of pieces){c.save();c.translate(p.x,p.y);c.rotate(p.rot);c.globalAlpha=Math.min(1,(p.life-p.age)/.16);polygon(p.points);c.fillStyle=p.color;c.fill();c.strokeStyle='#fff6df';c.lineWidth=1.4;c.stroke();c.restore()}}
function drawCore(){let r=42+Math.min(stage,4)*15,col=['#b79aff','#ffbf77','#78efd0','#f2a5d7','#e5e889'][Math.min(stage,4)],squash=Math.sin(corePulse*Math.PI)*.14;circle(195,315,r+15,'#ffffff08');c.save();c.translate(195,315);c.scale(1+squash,1-squash);let g=c.createRadialGradient(-r*.3,-r*.4,2,0,0,r);g.addColorStop(0,'#fffce7');g.addColorStop(.3,col);g.addColorStop(1,'#35425f');circle(0,0,r,g);
// At five a persistent six-petal shell; at ten a second interlocking eight-plate crown.
for(let layer=0;layer<Math.min(stage,2);layer++){let n=layer?8:6;for(let i=0;i<n;i++){let a=i/n*Math.PI*2-Math.PI/2+(layer?.18:0),rad=r*(layer?.91:.64),x=Math.cos(a)*rad,y=Math.sin(a)*rad;c.save();c.translate(x,y);c.rotate(a);polygon([[13,0],[0,8],[-10,0],[0,-8]]);c.fillStyle=layer?'#e7fff0':'#ffe2aa';c.fill();c.strokeStyle='#294f61';c.lineWidth=1.3;c.stroke();c.restore()}}
glyph(0,0,need,'#21394d');c.restore();text('进化 '+stage+'  ·  需要 '+need+' 点',195,225,14,accent);
if(grab){c.strokeStyle=grab.value===need?'#e6ffd6':'#ff7c88';c.lineWidth=2;c.beginPath();c.arc(grab.x,grab.y,grab.r+7,0,Math.PI*2);c.stroke();text(grab.value===need?'同纹 · 拖入核心':'纹路不同',195,600,13,c.strokeStyle)}
for(let f of fusions){let q=f.age/.3,e=1-Math.pow(1-q,3),x=f.x+(195-f.x)*e,y=f.y+(315-f.y)*e,ang=f.angle;c.save();c.translate(x,y);c.rotate(ang);c.scale(1+Math.sin(q*Math.PI)*.6,1-Math.sin(q*Math.PI)*.55);circle(0,0,29*(1-q),col);c.restore();for(let i=0;i<f.value+2;i++){let v=Math.max(0,Math.min(1,q*1.5-i*.12)),a=ang+v*Math.PI*1.4+i*.2,rr=(r+28)*(1-v);c.strokeStyle=col;c.globalAlpha=1-q;c.lineWidth=3;c.beginPath();c.arc(195,315,Math.max(1,rr),a-.32,a);c.stroke();circle(195+Math.cos(a)*rr,315+Math.sin(a)*rr,5*(1-v)+1,'#fff9df');c.globalAlpha=1}}
}

const point=e=>{let r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*390/r.width,y:(e.clientY-r.top)*780/r.height}};
function move(p){if(!prev)return;let delta=Math.hypot(p.x-prev.x,p.y-prev.y);if(delta<.01)return;trail.push({...p,age:0});if(mode===1){let hits=bodies.filter(b=>t>=b.born&&b.eligible<=gesture&&facetHit(b,prev,p));for(let b of hits){input('swipe');hitThis=true;splitFacet(b,prev,p);bodies=bodies.filter(x=>x!==b);payoff(b.x,b.y);spawnCut(b.slot,.09);opportunity('replacement_90ms_other_targets_live')}}else if(mode===3&&grab){grab.x=Math.max(35,Math.min(355,p.x));grab.y=Math.max(170,Math.min(600,p.y))}prev=p}
canvas.onpointerdown=e=>{if(down)return;canvas.setPointerCapture(e.pointerId);gesture++;counted=false;hitThis=false;down=true;origin=prev=point(e);log('pointer_down',{gesture,...origin});if(mode===3)grab=bodies.find(b=>!b.returning&&Math.hypot(b.x-origin.x,b.y-origin.y)<=b.r);if(mode===2&&Math.hypot(origin.x-195,origin.y-610)>62){down=false;prev=null;log('input_rejected',{reason:'start_at_launcher'})}};
canvas.onpointermove=e=>{if(down)move(point(e))};canvas.onpointerup=e=>{if(!down)return;let p=point(e);move(p);let travel=Math.hypot(p.x-origin.x,p.y-origin.y);if(mode===2&&travel>18&&p.y<575){input('aim_release');let dx=p.x-195,dy=p.y-610,d=Math.hypot(dx,dy);shots.push({x:195,y:610,vx:dx/d*1000,vy:dy/d*1000,age:0,input:inputNo,gesture,hits:0});log('release',{input:inputNo});opportunity('launcher_immediate')}else if(mode===3&&grab&&travel>12){input('move_merge');if(Math.hypot(grab.x-195,grab.y-315)<65&&grab.value===need){fusions.push({x:grab.x,y:grab.y,age:0,value:grab.value,angle:Math.atan2(origin.y-315,origin.x-195)});log('fusion_started',{input:inputNo,value:grab.value,duration_ms:300});payoff(195,315,need);corePulse=1;need=need%3+1;satellites();opportunity('next_pattern_immediate')}else{grab.returning=true;grab.badUntil=t+.24;log('snapback_started',{value:grab.value});miss('wrong_pattern_or_drop')}}else if(mode===1&&travel>12&&!hitThis){input('swipe_miss');miss('no_facet')}grab=null;down=false;prev=null;log('pointer_up',{gesture})};canvas.onpointercancel=()=>{if(grab){grab.x=grab.homeX;grab.y=grab.homeY}down=false;grab=null;prev=null;log('pointer_cancel')};
document.querySelector('#retry').onclick=()=>{log('retry_input');reset()};document.querySelector('#sound').onclick=e=>{muted=!muted;e.target.textContent=muted?'声音 关':'声音 开';if(muted)stopAudio();else sound('action')};document.querySelector('#qa').onclick=()=>{document.querySelector('pre').textContent=JSON.stringify({build:BUILD,loop:mode,generation:3,clock:'performance.now; CPU render submission NOT photon/audio latency',events},null,2);document.querySelector('dialog').showModal()};document.querySelector('#close').onclick=()=>document.querySelector('dialog').close();document.querySelector('#export').onclick=()=>{let a=document.createElement('a'),url=URL.createObjectURL(new Blob([document.querySelector('pre').textContent],{type:'application/json'}));a.href=url;a.download='continuous-'+mode+'.json';a.click();URL.revokeObjectURL(url)};
function circle(x,y,r,color){c.fillStyle=color;c.beginPath();c.arc(x,y,r,0,Math.PI*2);c.fill()}
function text(s,x,y,size=14,color='#e8ffff',align='center'){c.textAlign=align;c.font=`${size}px system-ui`;c.fillStyle=color;c.fillText(s,x,y)}
function glyph(x,y,n,col='#fff8de'){for(let i=0;i<n;i++)circle(x+(i-(n-1)/2)*10,y,2.6,col)}
function jewel(b){c.save();c.translate(b.x,b.y);c.rotate(b.a||0);let g=c.createLinearGradient(-b.r,-b.r,b.r,b.r);g.addColorStop(0,'#efffff');g.addColorStop(.25,accent);g.addColorStop(1,'#24455c');c.fillStyle=g;c.shadowColor=accent;c.shadowBlur=14;c.beginPath();if(b.type==='facet'){c.moveTo(0,-b.r);c.lineTo(b.r,0);c.lineTo(0,b.r);c.lineTo(-b.r,0);c.closePath()}else c.arc(0,0,b.r,0,Math.PI*2);c.fill();c.shadowBlur=0;c.strokeStyle='#ffffff85';c.lineWidth=1;c.stroke();if(b.value)glyph(0,0,b.value);if(b.badUntil>t){c.strokeStyle='#ff6b7c';c.lineWidth=4;c.beginPath();c.arc(0,0,b.r+3,0,Math.PI*2);c.stroke()}if(b.charged){c.strokeStyle='#fff9d1';c.lineWidth=3;c.beginPath();c.arc(0,0,b.r+5+Math.sin(t*20)*2,0,Math.PI*2);c.stroke()}if(b.type==='target'){c.strokeStyle='#233247';c.lineWidth=3;c.beginPath();c.arc(0,0,15,0,Math.PI*2);c.stroke()}c.restore()}
document.addEventListener('visibilitychange',()=>{last=performance.now();log(document.hidden?'hidden_suspend':'visible_resume');if(document.hidden){down=false;prev=null;if(grab){grab.x=grab.homeX;grab.y=grab.homeY}grab=null}});
function frame(now){let dt=(now-last)/1000;last=now;if(document.hidden){requestAnimationFrame(frame);return}if(dt>.25){log('long_stall_suspend',{ms:dt*1000});dt=0}t+=dt;let steps=Math.max(1,Math.ceil(dt*120)),h=dt/steps;for(let k=0;k<steps;k++){for(let b of bodies){if(b.type==='facet'){let age=t-b.born;b.x=b.baseX+Math.sin(age*1.6+b.phase)*25;b.y=b.baseY+Math.sin(age*2+b.phase)*27;b.a+=h*.38}else if(b.type==='target'){b.x+=(b.tx-b.x)*(1-Math.exp(-18*h));b.y+=(b.ty-b.y)*(1-Math.exp(-18*h))}else if(b.returning){b.x+=(b.homeX-b.x)*(1-Math.exp(-28*h));b.y+=(b.homeY-b.y)*(1-Math.exp(-28*h));if(Math.hypot(b.x-b.homeX,b.y-b.homeY)<1){b.x=b.homeX;b.y=b.homeY;b.returning=false;log('snapback_complete')}}}for(let s of shots){s.x+=s.vx*h;s.y+=s.vy*h;s.age+=h;let hit=bodies.find(b=>b.type==='target'&&!b.charged&&Math.hypot(s.x-b.x,s.y-b.y)<b.r+8);if(hit)triggerChain(hit,s)}shots=shots.filter(s=>{if(s.age>2||s.y<120||s.x<0||s.x>390){if(!s.hits){log('shot_miss',{input:s.input});miss('shot_missed')}return false}return true})}
for(let item of chainQueue.filter(q=>q.at<=t)){if(bodies.includes(item.b)){let saved=inputNo,gs=gesture;inputNo=item.input;gesture=item.gesture;bodies=bodies.filter(b=>b!==item.b);fracture(item);payoff(item.b.x,item.b.y);let chain=chains.get(item.id);if(chain&&--chain.left===0){labels.push({x:195,y:245,age:0,text:chain.total===1?'单点击破':'清链 ×'+chain.total});rings.push({x:item.b.x,y:item.b.y,age:0,big:true});sound('combo');log('chain_cleared',{id:item.id,input:chain.input,targets:chain.total});chains.delete(item.id);}log('chain_contact',{input:item.input,slot:item.b.slot,at:t,x:item.b.x,y:item.b.y});inputNo=saved;gesture=gs}}chainQueue=chainQueue.filter(q=>q.at>t);if(needsRefresh&&chainQueue.length===0){wave++;refreshTargets();needsRefresh=false}
pieces=pieces.filter(p=>(p.age+=dt)<p.life);for(let p of pieces){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=310*dt;p.rot+=p.spin*dt}fusions=fusions.filter(f=>{f.age+=dt;if(f.age>=.3){log('fusion_complete',{value:f.value});return false}return true});fx=fx.filter(p=>(p.age+=dt)<p.life);for(let p of fx){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=220*dt}rings=rings.filter(r=>(r.age+=dt)<.5);labels=labels.filter(l=>(l.age+=dt)<.75);trail=trail.filter(p=>(p.age+=dt)<.13);corePulse=Math.max(0,corePulse-dt*4);
let bg=c.createRadialGradient(195,340,20,195,390,480);bg.addColorStop(0,'#172f40');bg.addColorStop(1,'#060b15');c.fillStyle=bg;c.fillRect(0,0,390,780);c.fillStyle='#ffffff05';for(let i=0;i<45;i++)c.fillRect(i*97%390,i*151%780,1,1);
text('CONTINUOUS  /  0'+mode,26,38,10,'#809aa9','left');text(['切满连击 · 点亮共鸣','瞄准击穿 · 连锁清场','拖入同纹 · 连续进化'][mode-1],26,74,23,'#f1fbf7','left');text(['划过晶片，连续命中 5 次','从底部光核拖向目标，松手发射','把同样点数的光核拖进中心'][mode-1],26,102,12,'#a2bdc9','left');text(String(score).padStart(3,'0'),30,148,30,'#f0ffff','left');text('连击 '+streak,360,144,18,accent,'right');for(let i=0;i<5;i++){c.fillStyle=i<successes%5?accent:'#2b3f4c';c.fillRect(27+i*69,165,59,4)}
c.save();if(shake>0){c.translate(Math.sin(t*113)*shake,Math.cos(t*97)*shake*.5);shake=Math.max(0,shake-dt*45)}
if(mode===2){c.strokeStyle='#ffbd8038';c.lineWidth=2;c.beginPath();for(let [a,b]of links){let p=bodies.find(n=>n.slot===a),q=bodies.find(n=>n.slot===b);if(p&&q){c.moveTo(p.x,p.y);c.lineTo(q.x,q.y)}}c.stroke();c.strokeStyle='#ffffff12';c.beginPath();c.moveTo(195,185);c.lineTo(195,575);c.stroke();circle(195,610,34,'#20364a');circle(195,610,22,accent);circle(195,610,9,'#fff3dc');if(down&&prev){let dx=prev.x-195,dy=prev.y-610,d=Math.hypot(dx,dy)||1;c.setLineDash([4,8]);c.strokeStyle=accent;c.lineWidth=2;c.beginPath();c.moveTo(195,610);c.lineTo(195+dx/d*350,610+dy/d*350);c.stroke();c.setLineDash([])}}
if(mode===3)drawCore();
for(let item of chainQueue){if(!item.from)continue;let q=Math.max(0,Math.min(1,(t-item.start)/(item.at-item.start))),x=item.from.x+(item.b.x-item.from.x)*q,y=item.from.y+(item.b.y-item.from.y)*q;c.strokeStyle='#ffdc91';c.lineWidth=3;c.beginPath();c.moveTo(item.from.x,item.from.y);c.lineTo(x,y);c.stroke();circle(x,y,6,'#fffce3')}for(let b of bodies)if(t>=b.born||b.born===undefined)jewel(b);for(let s of shots){circle(s.x,s.y,8,'#fff3db');circle(s.x-s.vx*.018,s.y-s.vy*.018,4,accent)}drawPieces();for(let p of fx){c.globalAlpha=1-p.age/p.life;if(p.shard){c.save();c.translate(p.x,p.y);c.rotate(p.a);c.fillStyle=accent;c.beginPath();c.moveTo(-p.r,0);c.lineTo(p.r,0);c.lineTo(0,p.r*p.sign);c.closePath();c.fill();c.restore()}else circle(p.x,p.y,p.r,accent)}for(let r of rings){c.globalAlpha=1-r.age/.5;c.strokeStyle=accent;c.lineWidth=r.big?4:2;c.beginPath();c.arc(r.x,r.y,8+r.age*(r.big?380:150),0,Math.PI*2);c.stroke()}c.globalAlpha=1;if(trail.length>1&&mode===1){c.strokeStyle='#efffff';c.lineWidth=4;c.lineCap='round';c.beginPath();trail.forEach((p,i)=>i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y));c.stroke()}for(let l of labels){c.globalAlpha=1-l.age/.75;text(l.text,l.x,l.y-l.age*55,l.text.startsWith('+')?19:28,accent)}c.globalAlpha=1;c.restore();if(flare>0){c.fillStyle=`rgba(210,245,255,${flare})`;c.fillRect(0,180,390,455);flare=Math.max(0,flare-dt)}
if(missFlash>0){c.strokeStyle='#ff6b7c';c.lineWidth=3;c.globalAlpha=missFlash/.22;c.strokeRect(16,182,358,450);c.globalAlpha=1;missFlash=Math.max(0,missFlash-dt)}text('已行动 '+inputNo+' 次  ·  共鸣 '+stage,195,677,14,'#b2cdd4');text('GEN 3  /  INTERNAL CRAFT LOOP',195,703,10,'#607d8e');for(let p of pending)log('render_submitted',{kind:p.kind,delay_ms:+(performance.now()-p.at).toFixed(2)});pending=[];requestAnimationFrame(frame)}reset();requestAnimationFrame(frame);



