const mode=Math.max(1,Math.min(3,Number(new URLSearchParams(location.search).get('exercise'))||1));
const canvas=document.querySelector('canvas'),ctx=canvas.getContext('2d');const W=390,H=780;canvas.width=W*2;canvas.height=H*2;ctx.scale(2,2);
const colors=['#72f8df','#ffa976','#c7acff'],accent=colors[mode-1],names=['CHROMA / SHEAR','TENSION / RELEASE','MATTER / UNION'];
let events=[],run=0,start=performance.now(),last=start,t=0,bodies=[],particles=[],rings=[],trail=[],pending=[],shake=0,flash=0,freeze=0,down=false,previous=null,grab=null,score=0,readyAt=0,audio=null,muted=false;
try{audio=new AudioContext()}catch{};
const log=(event,data={})=>events.push({run,event,ms:+(performance.now()-start).toFixed(2),...data});
function tone(kind){if(muted)return;try{audio??=new AudioContext();audio.resume();const now=audio.currentTime;[0,1,2].forEach(i=>{let o=audio.createOscillator(),g=audio.createGain();o.type=i===2?'triangle':'sine';let f=kind==='cut'?680:kind==='merge'?220:90;o.frequency.setValueAtTime(f*(1+i*.501),now+i*.012);o.frequency.exponentialRampToValueAtTime(f*.45,now+.22);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(.055/(i+1),now+.006+i*.012);g.gain.exponentialRampToValueAtTime(.0001,now+.32+i*.07);o.connect(g).connect(audio.destination);o.start(now);o.stop(now+.6)});log('audio_scheduled',{kind,context_state:audio.state,base_latency_ms:audio.baseLatency*1000,audible_onset:'UNKNOWN'})}catch(e){log('audio_unavailable',{message:e.message})}}
function reset(){run++;t=0;score=0;particles=[];rings=[];trail=[];pending=[];freeze=0;shake=0;flash=0;grab=null;down=false;readyAt=0;bodies=mode===1?[{x:105,y:355,r:35,a:-.3},{x:195,y:315,r:38,a:.1},{x:285,y:355,r:35,a:.4}]:mode===2?[{x:195,y:270,r:32,vx:0,vy:0,held:true}]:[{x:105,y:405,r:42,vx:0,vy:0},{x:285,y:405,r:42,vx:0,vy:0}];log('ready');pending.push({kind:'ready',at:performance.now()})}
function burst(x,y,n=32){for(let i=0;i<n;i++){let a=i/n*Math.PI*2+Math.random()*.25,s=80+Math.random()*220;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,age:0,life:.3+Math.random()*.4,r:1+Math.random()*3})}rings.push({x,y,age:0});shake=5;flash=.11;freeze=.038;log('impact',{x,y});pending.push({kind:'impact',at:performance.now()})}
const dist=(p,a,b)=>{let dx=b.x-a.x,dy=b.y-a.y,q=Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/(dx*dx+dy*dy||1)));return Math.hypot(p.x-a.x-q*dx,p.y-a.y-q*dy)};
function act(p){if(!previous){previous=p;return}trail.push({...p,age:0});if(mode===1){for(const b of bodies){if(!b.cut&&dist(b,previous,p)<b.r){b.cut=true;b.cutAt=t;let angle=Math.atan2(p.y-previous.y,p.x-previous.x)-b.a;b.normal={x:-Math.sin(angle),y:Math.cos(angle)};let px=(previous.x-b.x)*Math.cos(b.a)+(previous.y-b.y)*Math.sin(b.a),py=-(previous.x-b.x)*Math.sin(b.a)+(previous.y-b.y)*Math.cos(b.a);b.plane=px*b.normal.x+py*b.normal.y;b.vx=(p.x-previous.x)*7;b.vy=-100;score++;burst(b.x,b.y,25);tone('cut');log('cut',{input_to_logic_ms:performance.now()-p.at});if(score===3){readyAt=t+.72;log('payoff')}}}}else if(mode===2){let b=bodies[0];if(b.held&&dist({x:195,y:180},previous,p)<65&&Math.min(previous.x,p.x)<=195&&Math.max(previous.x,p.x)>=195){b.held=false;b.releaseAt=t;log('release',{input_to_logic_ms:performance.now()-p.at});tone('cut');rings.push({x:195,y:p.y,age:0});pending.push({kind:'release',at:performance.now()})}}else if(grab){grab.target={x:p.x,y:p.y}}previous=p}
const point=e=>{let r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height,at:performance.now()}};
canvas.onpointerdown=e=>{canvas.setPointerCapture(e.pointerId);down=true;previous=point(e);log('pointer_down',{x:previous.x,y:previous.y});tone('touch');if(mode===3)grab=bodies.find(b=>!b.merged&&Math.hypot(b.x-previous.x,b.y-previous.y)<b.r+12);if(grab)grab.target=previous};canvas.onpointermove=e=>{if(down)act(point(e))};canvas.onpointerup=e=>{if(down)act(point(e));down=false;previous=null;if(grab)grab.target=null;grab=null;log('pointer_up')};canvas.onpointercancel=()=>{down=false;previous=null;if(grab)grab.target=null;grab=null;log('pointer_cancel')};
document.querySelector('#retry').onclick=()=>{log('retry_input');reset()};document.querySelector('#sound').onclick=e=>{muted=!muted;e.target.textContent=muted?'Sound off':'Sound on';if(!muted)tone('merge')};document.querySelector('#measure').onclick=()=>{document.querySelector('pre').textContent=JSON.stringify({build:'craft-v5-0.2.2',exercise:mode,clock:'performance.now; CPU render submission, not photon latency',events},null,2);document.querySelector('dialog').showModal()};document.querySelector('#close').onclick=()=>document.querySelector('dialog').close();document.querySelector('#export').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([document.querySelector('pre').textContent],{type:'application/json'}));a.download=`craft-${mode}-timing.json`;a.click();URL.revokeObjectURL(a.href)};
function circle(x,y,r,fill){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle=fill;ctx.fill()}
function shape(b,offset=0){ctx.save();ctx.translate(b.x+offset,b.y);ctx.rotate(b.a||0);let g=ctx.createLinearGradient(-b.r,-b.r,b.r,b.r);g.addColorStop(0,'#ffffff');g.addColorStop(.18,b.merged?'#ffce87':accent);g.addColorStop(1,b.merged?'#854569':'#234c67');ctx.fillStyle=g;ctx.shadowColor=b.merged?'#ffce87':accent;ctx.shadowBlur=18;if(mode===1){ctx.beginPath();ctx.moveTo(0,-b.r);ctx.lineTo(b.r,0);ctx.lineTo(0,b.r);ctx.lineTo(-b.r,0);ctx.closePath();ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='#ffffffaa';ctx.beginPath();ctx.moveTo(0,-b.r);ctx.lineTo(0,b.r);ctx.stroke()}else{ctx.beginPath();ctx.arc(0,0,b.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='#ffffff80';ctx.lineWidth=2;ctx.beginPath();ctx.arc(-2,-2,b.r*.7,3.5,5.8);ctx.stroke();if(b.merged){ctx.strokeStyle='#fff6d7';ctx.lineWidth=2;ctx.beginPath();for(let i=0;i<6;i++){let a=i*Math.PI/3-Math.PI/2;i?ctx.lineTo(Math.cos(a)*22,Math.sin(a)*22):ctx.moveTo(Math.cos(a)*22,Math.sin(a)*22)}ctx.closePath();ctx.stroke();circle(0,0,6,'#fff6d7')}}ctx.restore()}
document.addEventListener('visibilitychange',()=>{last=performance.now();log(document.hidden?'hidden_suspend':'visible_resume')});
function shard(b,sign){let n=b.normal,sep=(t-b.cutAt)*90;ctx.save();ctx.translate(b.x,b.y);ctx.rotate(b.a);ctx.translate(n.x*sep*sign,n.y*sep*sign);let q={x:-n.y,y:n.x},v=300;let ox=n.x*b.plane,oy=n.y*b.plane;ctx.beginPath();ctx.moveTo(ox+q.x*v,oy+q.y*v);ctx.lineTo(ox-q.x*v,oy-q.y*v);ctx.lineTo(ox-q.x*v+n.x*v*sign,oy-q.y*v+n.y*v*sign);ctx.lineTo(ox+q.x*v+n.x*v*sign,oy+q.y*v+n.y*v*sign);ctx.closePath();ctx.clip();shape({...b,x:0,y:0,a:0});ctx.restore()}
function frame(now){let elapsed=(now-last)/1000;last=now;if(document.hidden){requestAnimationFrame(frame);return}let dt=elapsed>.25?0:elapsed;if(elapsed>.25)log('long_stall_suspend',{elapsed_ms:elapsed*1000});t+=dt;let steps=Math.max(1,Math.ceil(dt*120));for(let k=0;k<steps;k++){let part=dt/steps;let sim=freeze>0?0:part;freeze-=part;
 if(mode===1){for(const b of bodies){if(!b.cut){b.y+=Math.sin(t*2+b.x)*sim*12;b.a+=sim*.12}else{b.vy+=600*sim;b.y+=b.vy*sim;b.x+=b.vx*sim*.08;b.a+=sim*2}}}
 if(mode===2){let b=bodies[0];if(!b.held&&!b.landed){b.vy+=1600*sim;b.y+=b.vy*sim;if(b.y>=548){b.y=548;b.landed=true;b.landAt=t;score=1;readyAt=t+.85;burst(b.x,580,55);tone('impact');log('payoff',{impact_speed:Math.round(b.vy)})}}}
 if(mode===3){for(const b of bodies){if(b.target){b.vx+=(b.target.x-b.x)*300*sim;b.vy+=(b.target.y-b.y)*300*sim}b.vx*=Math.exp(-20*sim);b.vy*=Math.exp(-20*sim);b.x=Math.max(50,Math.min(340,b.x+b.vx*sim));b.y=Math.max(180,Math.min(570,b.y+b.vy*sim))}if(bodies.length===2&&Math.hypot(bodies[0].x-bodies[1].x,bodies[0].y-bodies[1].y)<84){let x=(bodies[0].x+bodies[1].x)/2,y=(bodies[0].y+bodies[1].y)/2;bodies=[{x,y,r:60,vx:0,vy:0,merged:true,born:t}];grab=null;score=1;readyAt=t+.9;burst(x,y,48);tone('merge');log('payoff')}}
 }
 particles=particles.filter(p=>(p.age+=dt)<p.life);for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=200*dt}rings=rings.filter(r=>(r.age+=dt)<.55);trail=trail.filter(p=>(p.age+=dt)<.17);
 ctx.clearRect(0,0,W,H);let bg=ctx.createRadialGradient(195,360,10,195,390,460);bg.addColorStop(0,mode===2?'#322a33':'#162b3d');bg.addColorStop(1,'#060b15');ctx.fillStyle=bg;ctx.fillRect(0,0,W,H);ctx.fillStyle='#ffffff04';for(let i=0;i<60;i++)ctx.fillRect((i*97)%390,(i*137)%780,1,1);
 ctx.fillStyle='#8495a8';ctx.font='10px system-ui';ctx.fillText('CRAFT CALIBRATION     /     0'+mode,28,53);ctx.fillStyle='#eef2f2';ctx.font='24px system-ui';ctx.fillText(names[mode-1],28,89);ctx.fillStyle='#9aabbb';ctx.font='12px system-ui';ctx.fillText(['Swipe through the suspended facets','Sever the filament. Feel the landing.','Bring the two fields into contact'][mode-1],28,117);
 ctx.save();if(shake>0){ctx.translate(Math.sin(t*110)*shake,Math.cos(t*97)*shake*.6);shake=Math.max(0,shake-dt*35)}
 ctx.strokeStyle='#ffffff10';ctx.lineWidth=1;ctx.strokeRect(24,150,342,480);
 if(mode===2){let b=bodies[0];ctx.strokeStyle=accent;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(195,150);ctx.lineTo(195,b.held?b.y-b.r:150+Math.max(0,100-(t-(b.releaseAt||0))*150));ctx.stroke();ctx.fillStyle='#172838';ctx.fillRect(65,580,260,15);ctx.fillStyle=accent;ctx.fillRect(65,580,260,3);if(b.landed){ctx.save();ctx.translate(b.x,b.y+b.r);let a=Math.max(0,1-(t-b.landAt)/.35);ctx.scale(1+a*.25,1-a*.2);shape({...b,x:0,y:-b.r});ctx.restore()}else shape(b)}else for(const b of bodies){if(mode===1&&b.cut){ctx.save();ctx.globalAlpha=Math.max(0,1-(t-b.cutAt)/.75);shard(b,-1);shard(b,1);ctx.restore()}else if(b.merged){let a=Math.exp(-(t-b.born)*9)*Math.sin((t-b.born)*23)*.2;ctx.save();ctx.translate(b.x,b.y);let squeeze=.22*Math.exp(-(t-b.born)*22);ctx.scale(1+a+squeeze*.4,1-a-squeeze);shape({...b,x:0,y:0});ctx.restore()}else shape(b)}
 for(const r of rings){ctx.strokeStyle=accent;ctx.globalAlpha=1-r.age/.55;ctx.lineWidth=3*(1-r.age/.55);ctx.beginPath();ctx.arc(r.x,r.y,8+r.age*210,0,Math.PI*2);ctx.stroke()}ctx.globalAlpha=1;
 for(const p of particles){ctx.globalAlpha=1-p.age/p.life;circle(p.x,p.y,p.r,accent)}ctx.globalAlpha=1;if(trail.length>1){ctx.strokeStyle='#ffffff';ctx.lineWidth=4;ctx.lineCap='round';ctx.shadowColor=accent;ctx.shadowBlur=16;ctx.beginPath();trail.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();ctx.shadowBlur=0}ctx.restore();if(flash>0){ctx.fillStyle=`rgba(220,245,255,${flash})`;ctx.fillRect(0,140,W,490);flash-=dt}
 ctx.textAlign='center';ctx.fillStyle=score?'#efffff':'#678091';ctx.font='13px system-ui';ctx.fillText(score?(mode===1?`${score} / 3  •  clean separation`:'CONTACT  /  TRANSFORMED'):'ONE GESTURE · ONE MATERIAL RESPONSE',195,674);ctx.fillStyle='#566577';ctx.font='10px system-ui';ctx.fillText('INTERNAL STUDY — NOT A PRODUCT',195,698);ctx.textAlign='left';
 for(const p of pending)log('render_submitted',{kind:p.kind,delay_ms:+(performance.now()-p.at).toFixed(2)});pending=[];
 if(readyAt&&t>=readyAt){readyAt=0;log('settled_after_payoff');/* Manual retry remains available throughout. */}requestAnimationFrame(frame)}reset();requestAnimationFrame(frame);





