import {Game,LAYOUTS} from './engine.js';import {Telemetry} from './telemetry.js';
const canvas=document.querySelector('canvas'),ctx=canvas.getContext('2d'),q=new URLSearchParams(location.search),tel=new Telemetry(q.get('qa')==='1',q.get('novice')==='1');
let game=new Game(q.get('qa')==='1'?q.get('seed')||'C':'C'),travelAt=0,now=0,drag=null,selected=false,firstTouch=false,impactAt=-9999,impactPoint=null,sound=false,audio=null,terminalAt=0;
tel.newRun(game.seed);setInterval(()=>tel.flush(),4000);window.addEventListener('pagehide',()=>{tel.event('exit');tel.flush();});
const P={first:[[78,348],[280,348]],short:[[78,338],[294,338]],long:[[78,338],[78,207],[240,207],[294,338]]};
const duration=()=>game.route==='FIRST'?4400:game.route==='LONG'?11000:8000;
function along(points,t){let lengths=points.slice(1).map((p,i)=>Math.hypot(p[0]-points[i][0],p[1]-points[i][1])),total=lengths.reduce((a,b)=>a+b,0),d=Math.max(0,Math.min(1,t))*total;for(let i=0;i<lengths.length;i++){if(d<=lengths[i]){let f=d/lengths[i];return [points[i][0]+(points[i+1][0]-points[i][0])*f,points[i][1]+(points[i+1][1]-points[i][1])*f];}d-=lengths[i];}return points.at(-1);}
const routePoints=()=>game.route==='FIRST'?P.first:game.route==='LONG'?P.long:P.short;
function progress(){return Math.min(1,(now-travelAt)/duration());}
function carPoint(){if(game.phase==='FIRST')return P.first[0];if(game.phase==='CHOICE')return P.short[0];if(game.phase==='TRAVEL'||game.phase==='LOST')return along(routePoints(),game.phase==='LOST'?game.stoppedAt:progress());return [304,338];}
function platePoint(){if(game.plate==='FIRST_BRIDGE')return game.cart==='START'?[180,362]:[76,440];if(game.plate==='SHORT_BRIDGE')return [184,352];const c=carPoint();return [c[0],c[1]-37];}
function tone(freq=440,length=.12){if(!sound)return;audio??=new AudioContext();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='triangle';o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.55,audio.currentTime+length);g.gain.setValueAtTime(.12,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+length);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+length);}
function path(points,color,width,dash=[]){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.strokeStyle=color;ctx.lineWidth=width;ctx.lineCap='round';ctx.lineJoin='round';ctx.setLineDash(dash);ctx.stroke();ctx.setLineDash([]);}
function box(x,y,w,h,r,color){ctx.fillStyle=color;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill();}
function poly(points,color){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.closePath();ctx.fillStyle=color;ctx.fill();}
function circle(x,y,r,color){ctx.fillStyle=color;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();}
function plate(x,y,glow=false){ctx.save();if(glow){ctx.shadowColor='#ffd997';ctx.shadowBlur=14;}box(x-46,y-11,92,22,7,'#512e30');box(x-46,y-15,92,22,7,'#f39b4e');box(x-40,y-12,80,4,2,'#ffe1a0');for(let z=-32;z<=32;z+=64)circle(x+z,y-3,3,'#b75438');ctx.strokeStyle='#fff0bb';ctx.lineWidth=5;ctx.beginPath();ctx.roundRect(x-12,y-25,24,13,5);ctx.stroke();ctx.restore();}
function car(x,y){ctx.save();ctx.translate(x,y);if(game.phase==='LOST')ctx.scale(1.15,.6);let bob=game.phase==='TRAVEL'?Math.sin(now/70)*1.4:Math.sin(now/300)*.6;ctx.translate(0,bob);circle(-20,7,10,'#102a32');circle(20,7,10,'#102a32');circle(-20,7,4,'#92b4b3');circle(20,7,4,'#92b4b3');box(-31,-28,62,32,12,'#e4debe');box(-26,-30,53,22,9,'#9dc7bd');box(-12,-24,31,14,6,'#25444a');circle(2,-17,2.5,'#fff4d5');circle(12,-17,2.5,'#fff4d5');box(26,-15,7,8,3,'#ffe29a');if(game.plate==='ROOF'&&!drag&&!selected)plate(0,-37,game.phase==='FIRST');else path([[-24,-37],[24,-37]],'#587c77',5);ctx.restore();}
function rock(x,y,small=false){ctx.save();ctx.translate(x,y);if(small)ctx.scale(.65,.65);poly([[-17,-15],[-6,-25],[14,-19],[22,-4],[11,12],[-12,9],[-23,-2]],'#7c8988');path([[-5,-23],[2,-8],[-5,0],[3,9]],'#344f56',3);path([[-18,-15],[-7,-22],[8,-19]],'#c0c6ae',2);ctx.restore();}
function cabin(){box(275,295,66,55,5,'#704d43');poly([[265,298],[308,262],[350,298]],'#f7bf74');box(288,309,22,40,6,game.phase==='WON'?'#fff1ad':'#eaa951');box(318,310,12,12,2,'#ffe6a0');if(game.phase==='WON'){ctx.save();ctx.globalAlpha=.25;poly([[299,316],[247,372],[349,372]],'#ffe08b');ctx.restore();}}
function targets(){return game.phase==='FIRST'?[['FIRST_BRIDGE',180,354]]:[['ROOF',78,301],['SHORT_BRIDGE',184,350]];}
function snap(p){if(!p)return null;return targets().find(t=>Math.abs(p.x-t[1])<65&&Math.abs(p.y-t[2])<42)?.[0]||null;}
function background(second){let g=ctx.createLinearGradient(0,0,0,510);g.addColorStop(0,'#72aca8');g.addColorStop(.5,'#c5d4b5');g.addColorStop(1,'#173a4a');ctx.fillStyle=g;ctx.fillRect(0,0,360,510);circle(282,60,32,'#e8d7a3');poly([[0,210],[47,76],[119,191],[184,106],[272,218],[333,129],[360,188],[360,510],[0,510]],'#649393');poly([[0,292],[80,172],[148,302],[209,177],[302,327],[360,250],[360,510],[0,510]],'#426c77');for(let i=0;i<7;i++){let y=470+(i*17+now/120)%60;path([[130,y],[230,y-10]],'#285365',2);}if(second){path(P.long,'#244c53',34);path(P.long,'#8aa68f',20);path([[0,354],[132,354]],'#1c454c',39);path([[236,354],[360,354]],'#1c454c',39);path([[0,350],[139,350]],'#b6b596',14);path([[229,350],[360,350]],'#b6b596',14);poly([[0,370],[139,370],[95,510],[0,510]],'#2e5961');poly([[229,370],[360,370],[360,510],[277,480]],'#2e5961');path([[0,448],[30,448]],'#a3ad91',12);path([[122,448],[146,448]],'#a3ad91',12);cabin();}else{poly([[0,361],[134,361],[110,510],[0,510]],'#315c60');poly([[226,361],[360,361],[360,510],[258,510]],'#315c60');path([[0,361],[134,361]],'#c1b69b',14);path([[226,361],[360,361]],'#c1b69b',14);box(281,319,5,36,2,'#4b7370');poly([[286,319],[309,326],[286,334]],'#edc06e');} }
function draw(){ctx.clearRect(0,0,360,510);let second=game.cart!=='START';background(second);
 if(second){for(const route of ['SHORT','LONG']){let count=LAYOUTS[game.seed][route];for(let i=0;i<count;i++){let f=count===2?[.39,.72][i]:.56,p=along(route==='LONG'?P.long:P.short,f),active=game.route===route&&(game.phase==='TRAVEL'||game.phase==='LOST'||game.phase==='WON');if(active&&i<game.impacts)continue;let fall=active?Math.max(0,Math.min(1,(progress()-(f-.09))/.09)):0;rock(p[0],p[1]-82+fall*69);if(fall===0){path([[p[0]-6,p[1]-54],[p[0]-6,p[1]-48]],'#d7cba1',2);circle(p[0]+8,p[1]-44+(now/70)%9,1.4,'#e9d7a9');} }} }
 if((drag||selected)&&['FIRST','CHOICE'].includes(game.phase)){const target=snap(drag?.p);for(const [id,x,y] of targets()){ctx.save();ctx.globalAlpha=id===target?.9:.38;box(x-52,y-28,104,56,12,'#ffedb0');ctx.restore();}if(target){let pts=target==='FIRST_BRIDGE'?P.first:target==='ROOF'?P.long:P.short;path(pts,'#fff3bd',5,[8,9]);let p=along(pts,(now%1800)/1800);ctx.save();ctx.globalAlpha=.45;box(p[0]-22,p[1]-22,44,20,8,'#fff8cf');ctx.restore();}}
 if(!drag&&!selected&&game.plate.includes('BRIDGE')){let p=platePoint();plate(...p,game.phase==='CHOICE');if(game.phase==='CHOICE'){ctx.save();ctx.strokeStyle='#ffd99c';ctx.globalAlpha=.35+.15*Math.sin(now/250);ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(p[0],p[1]-9,57,35,0,0,7);ctx.stroke();ctx.restore();}}
 let cp=carPoint();if(game.phase!=='WON'||now-terminalAt<700)car(...cp);if(drag||selected){const t=snap(drag?.p),p=t?targets().find(v=>v[0]===t).slice(1):drag?[drag.p.x,drag.p.y-12]:platePoint();plate(...p,true);}
 if(now-impactAt<850&&impactPoint){let f=(now-impactAt)/850;for(let i=0;i<11;i++){let angle=i*2.4;circle(impactPoint[0]+Math.cos(angle)*f*80,impactPoint[1]-20+Math.sin(angle)*f*55+f*f*50,4*(1-f),'#ffe0a0');}if(game.plate==='BROKEN'){for(let j=0;j<6;j++){let sx=impactPoint[0]+(j-2.5)*(10+f*22),sy=impactPoint[1]-37-Math.sin(f*Math.PI)*30+f*f*55;poly([[sx-8,sy],[sx+5,sy-5],[sx+10,sy+6],[sx-5,sy+4]],'#f39b4e');}rock(impactPoint[0]+f*110,impactPoint[1]-40-Math.sin(f*Math.PI)*90,true);}}
 if(game.phase==='LOST'&&impactPoint){rock(impactPoint[0],impactPoint[1]-18);if(game.plate==='BROKEN'){poly([[impactPoint[0]-40,impactPoint[1]+13],[impactPoint[0]-27,impactPoint[1]+8],[impactPoint[0]-20,impactPoint[1]+18]],'#f39b4e');}}if(game.phase==='WON'){for(let i=0;i<12;i++){let f=((now-terminalAt)/1900+i/12)%1;circle(300+Math.sin(i*3)*f*55,310-f*90,2,'#fff0a9');}} }
function tick(t){now=t;if(game.phase==='TRAVEL'){const f=progress();if(game.route!=='FIRST'){const n=LAYOUTS[game.seed][game.route],due=n===2?[.39,.72]:[.56];if(game.impacts<n&&f>=due[game.impacts]){impactPoint=along(routePoints(),due[game.impacts]);let hit=game.hit();impactAt=now;tone(game.phase==='LOST'?90:620,.32);tel.event('impact',hit);if(game.phase==='LOST'){game.stoppedAt=due[game.impacts-1];end('lost');}}}if(f>=1&&game.phase==='TRAVEL'){const first=game.route==='FIRST';if(game.finish()){if(first){tel.event('first_crossing');document.querySelector('#caption').textContent='';tone(660,.2);}else end('won');}}}draw();requestAnimationFrame(tick);}
function end(name){terminalAt=now;tel.event(name,{route:game.route});tel.flush();document.querySelector('#caption').textContent=name==='won'?'到家了':'还差一点';const b=document.querySelector('#again');b.hidden=false;b.textContent=name==='won'?'再走一程 →':'再试一次 ↻';tone(name==='won'?880:100,.4);}
function point(e){const r=canvas.getBoundingClientRect();return {x:(e.clientX-r.left)*360/r.width,y:(e.clientY-r.top)*510/r.height};}
function onPlate(p){let [x,y]=platePoint();return Math.abs(p.x-x)<57&&Math.abs(p.y-y)<32;}
canvas.addEventListener('pointerdown',e=>{if(!firstTouch){firstTouch=true;tel.event('first_touch',{target:onPlate(point(e))?'plate':'scene'});}if(drag||!['FIRST','CHOICE'].includes(game.phase))return;const p=point(e);if(selected&&!onPlate(p)){if(game.begin(e.pointerId)){drag={id:e.pointerId,p,start:p,tapTarget:true};try{canvas.setPointerCapture(e.pointerId);}catch{}}return;}if(!onPlate(p)||!game.begin(e.pointerId))return;drag={id:e.pointerId,p,start:p,tapTarget:false};selected=false;try{canvas.setPointerCapture(e.pointerId);}catch{}tel.event('drag_start',{origin:game.plate});tone(440);});
canvas.addEventListener('pointermove',e=>{if(drag?.id===e.pointerId)drag.p=point(e);});
canvas.addEventListener('pointerup',e=>{if(drag?.id!==e.pointerId)return;const p=point(e),target=snap(p),wasTap=Math.hypot(p.x-drag.start.x,p.y-drag.start.y)<8&&!drag.tapTarget;let valid=game.drop(e.pointerId,wasTap?null:target);drag=null;selected=wasTap;tel.event('drag_end',{valid,target:wasTap?null:target});if(valid){selected=false;travelAt=now;tel.event(game.route==='FIRST'?'first_bridge':'choice',{route:game.route,layout:game.seed});tone(550,.18);} });
function cancel(e){if(drag?.id!==e.pointerId)return;game.cancel(e.pointerId);drag=null;selected=false;tel.event('drag_cancel');}canvas.addEventListener('pointercancel',cancel);canvas.addEventListener('lostpointercapture',cancel);
function restart(){document.querySelector('#log').open=false;const previous=game.seed;game=game.restart();drag=null;selected=false;firstTouch=false;impactAt=-9999;tel.newRun(game.seed,true,previous===game.seed);document.querySelector('#again').hidden=true;document.querySelector('#caption').textContent='';tone(330);}
document.querySelector('#reset').onclick=restart;document.querySelector('#again').onclick=restart;document.querySelector('#sound').onclick=()=>{sound=!sound;document.querySelector('#sound b').textContent=sound?'开':'关';document.querySelector('#sound').setAttribute('aria-label',sound?'关闭声音':'开启声音');tone();};
function resize(){const r=canvas.getBoundingClientRect(),d=devicePixelRatio||1;canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d);ctx.setTransform(canvas.width/360,0,0,canvas.height/510,0,0);}new ResizeObserver(resize).observe(canvas);resize();document.querySelector('#caption').textContent='';window.__B03={get state(){return {...game,drag:game.drag};},telemetry:tel};requestAnimationFrame(tick);

const log=document.querySelector('#log');function updateLog(){log.hidden=!tel.qa&&!['WON','LOST'].includes(game.phase);if(log.open)document.querySelector('#logtext').textContent=JSON.stringify({build:'v41-b03-0.1.0',session:tel.session,run:tel.run,seed:game.seed,qa:tel.qa,test_stage:tel.qa?'TECHNICAL_QA':tel.novice?'NOVICE_CHECK':'UNCLASSIFIED',status:tel.status,pending:tel.pending.length,events:tel.rows.map(r=>({event:r.event,id:r.uuid,run:r.properties.run_id,ms:r.properties.elapsed_ms}))},null,2);}setInterval(updateLog,500);log.addEventListener('toggle',updateLog);document.querySelector('#export').onclick=()=>{const u=URL.createObjectURL(new Blob([JSON.stringify({status:tel.status,pending:tel.pending.length,events:tel.rows},null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='b03-'+tel.session+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};updateLog();



