import {BUILD,create,act,tick,drain,weight,offers,returnTime} from './engine.js';
import {shape,fits,connected,incoming} from './home.js';import {painter} from './art.js';import {Telemetry} from './telemetry.js';
const $=id=>document.getElementById(id),params=new URLSearchParams(location.search),proof=Number(params.get('proof')),qa=params.get('qa')==='1';
const defs={1:{title:'再拿一件',tag:'01 / THE LAST TREASURE',line:'点宝物装车。重了会滑落，回程也更慢。',setup:'把眼前的发现带回去。裂缝深处，还有一件。',button:'推车进矿洞'},2:{title:'还有一只',tag:'02 / ONE MORE PASSENGER',line:'点动物接上船，点靠岸送回。大个子会让船更沉。',setup:'它们在屋顶等你。先接谁，由你决定。',button:'划船过去'},3:{title:'给家腾口气',tag:'03 / ROOM TO BREATHE',line:'点空位放木料。连到左下排口，一起冲走。',setup:'先扶好椅子。潮水带来的木料，快把家挤满了。',button:'扶好我的椅子'}};
let audio=null,sound=false;function tone(freq=440,length=.1,type='sine',gain=.035){if(!sound||!audio)return;try{const o=audio.createOscillator(),a=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.65,audio.currentTime+length);a.gain.setValueAtTime(gain,audio.currentTime);a.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+length);o.connect(a);a.connect(audio.destination);o.start();o.stop(audio.currentTime+length);}catch{}}
$('sound').onclick=async()=>{try{audio??=new (window.AudioContext||window.webkitAudioContext)();await audio.resume();sound=!sound;$('sound').textContent=sound?'声音 开':'声音 关';$('sound').setAttribute('aria-label',sound?'关闭声音':'开启声音');tone();}catch{$('sound').textContent='声音不可用';}};
$('build').textContent=BUILD;
let order=[1,2,3];try{const stored=sessionStorage.getItem('m003-order');if(stored)order=JSON.parse(stored);else{for(let i=2;i>0;i--){let j=crypto.getRandomValues(new Uint32Array(1))[0]%(i+1);[order[i],order[j]]=[order[j],order[i]];}sessionStorage.setItem('m003-order',JSON.stringify(order));}}catch{}
$('cards').innerHTML=order.map(n=>`<a class="card" href="?proof=${n}${qa?'&qa=1':''}"><span>一个约半分钟的小体验</span><b>${defs[n].title}</b><span>进入 →</span><i>${n===1?'◇':n===2?'≈':'⌂'}</i></a>`).join('');
if(defs[proof])run();
function run(){
 $('lobby').hidden=true;$('game').hidden=false;const d=defs[proof];document.title=d.title+' · 三个瞬间';$('title').textContent=d.title;$('chapter').textContent=d.tag;$('instruction').textContent=d.line;$('setupText').textContent=d.setup;$('start').textContent=d.button;
 let s=create(proof),attempt=0,hover=null,last=performance.now(),lastControls='',finished=false,decisionSince=performance.now(),selected=null;const paint=painter($('scene')),tel=new Telemetry(proof,qa);
 function status(){const x={build:BUILD,qa,session:tel.session,run:tel.run,events:tel.rows.length,acked:tel.acked,pending:tel.pending.length,status:tel.status,error:tel.error||null,audio:audio?.state||'off',actions:tel.actions};$('qa').textContent=(qa?'技术 QA · 不计入真人结果\n':'匿名记录\n')+JSON.stringify(x,null,2);}
 tel.onchange=status;status();setInterval(()=>tel.flush(),1700);
 function consume(){for(const e of drain(s)){if(e.type==='payoff'){tel.payoff(e);tone(660,.22);setTimeout(()=>tone(880,.22),80);decisionSince=performance.now();}else{tel.event(e.type,e);if(['cargo_slipped','capsize','owned_object_damaged'].includes(e.type))tone(130,.35,'triangle',.06);}}}
 function action(kind,arg){const before={cargo:weight(s),remaining:+(s.duration-s.t).toFixed(2),busy:s.busy};const res=act(s,kind,arg);if(res.ok){if(res.setup){decisionSince=performance.now();tel.event('entry_action',{kind,time_to_entry_ms:Math.round(performance.now()-tel.runStart)});}else{tel.action(kind,{target:arg??null,decision_latency_ms:Math.round(performance.now()-decisionSince),risk_context:before,coaching:'UNKNOWN'});decisionSince=performance.now();tone(kind==='drop'?210:370,.09);}consume();renderControls();}else{tel.event('input_error',{kind,target:arg??null,reason:res.reason});s.message=res.reason==='blocked_placement'?'这里放不下，换一个空位':res.reason==='drain_cooling'?'排口还在重新蓄力':res.reason==='outlet_disconnected'?'先把木料连到左下排口':'稍等，这个动作现在不能完成';tone(170,.06);}return res;}
 $('start').onclick=()=>{action('start');$('startcover').hidden=true;renderControls();};
 $('replay').onclick=()=>{tel.newRun(true);attempt++;s=create(proof,attempt%3);lastControls='';finished=false;hover=null;selected=null;decisionSince=performance.now();$('result').hidden=true;$('startcover').hidden=true;action('start');};
 $('export').onclick=()=>{const data={mission:'MISSION003',build:BUILD,qa,events:tel.rows};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=`mission003-proof${proof}-${tel.session}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
 function renderControls(){if(!s.started||s.done){$('controls').innerHTML='';$('subcontrols').innerHTML='';return;}let html='',sub='';const disabled=s.busy>0?'disabled':'';
 if(proof===1){html=offers(s).map((o,i)=>`<button data-kind="take" data-arg="${i}" ${disabled||s.depth>=6?'disabled':''}>取${o.name}<small>重量 ${o.weight} · 价值 ${o.value}</small></button>`).join('');sub=`<button data-kind="bank" ${disabled||!s.cargo.length?'disabled':''}>带回出口</button><button data-kind="drop" ${disabled||!s.cargo.length?'disabled':''}>放下最后一件</button>`;$('detail').textContent=`车内 ${s.cargo.length} 件 · 回程约 ${returnTime(s).toFixed(1)} 秒 · 已带回 ${s.bank.length} 件`;}
 if(proof===2){html=s.animals.filter(a=>['roof','raft'].includes(a.status)).map(a=>`<button data-kind="rescue" data-arg="${a.id}" ${disabled}>接${a.name}<small>${a.weight===3?'大个子':a.weight===2?'中等体型':'轻巧'}${a.status==='raft'?' · 浮木上':''}</small></button>`).join('');sub=`<button data-kind="bank" ${disabled||!s.cargo.length?'disabled':''}>靠岸，让它们安全</button>`;$('detail').textContent=s.cargo.length?`船上：${s.cargo.map(a=>a.name).join('、')}。${weight(s)>3?'再接大个子可能翻船。':'还留着一些干舷。'}`:'船空了，岸边的小动物还在等你。';}
 if(proof===3){const n=shape(s);html=`<button id="piece" aria-label="拿起下一块木料">下一块：${n.length}格 ${n.length===2?'▮▮':n[2]?.[0]===2?'▮▮▮':'▟'}<small>点房间空位放下 · 可旋转</small></button><button data-kind="drain" ${s.home.drainCD>0?'disabled':''}>${s.home.drainCD>0?'排口蓄力中':'打开排口'}<small>可冲走 ${connected(s).length} 格 · 之后闭合9秒</small></button>`;sub='<button data-kind="rotate">旋转木料</button>';const free=s.home.board.filter((v,i)=>v===0&&!s.home.anchors.some(a=>a.i===i)).length;$('detail').textContent=`${Math.ceil(s.home.tide)}秒后涌入${incoming(s).count}格木料 · 空位 ${free}格 · ${incoming(s).damage?incoming(s).damage.name+'将被压坏':'两侧虚线落木 · 中间留给你连接'}`;}
 const key=html+sub;if(key!==lastControls){$('controls').innerHTML=html;$('subcontrols').innerHTML=sub;lastControls=key;for(const b of document.querySelectorAll('[data-kind]'))b.onclick=()=>{if(b.dataset.kind==='rotate'){s.home.rotation=(s.home.rotation||0)+1;tel.event('piece_rotated');hover=null;renderControls();}else action(b.dataset.kind,b.dataset.arg===undefined?undefined:Number(b.dataset.arg));};const p=$('piece');if(p)p.onclick=()=>{s.message='点房间里的空位，木料会从这里开始摆放';};}}
 function point(e){const r=$('scene').getBoundingClientRect();return {x:(e.clientX-r.left)*400/r.width,y:(e.clientY-r.top)*400/r.height};}
 $('scene').addEventListener('pointermove',e=>{if(proof!==3)return;const {x,y}=point(e);const c=Math.floor((x-29)/69),r=Math.floor((y-29)/69);hover=c>=0&&c<5&&r>=0&&r<5?r*5+c:null;});
 $('scene').addEventListener('pointerleave',()=>hover=null);
 $('scene').addEventListener('pointerdown',e=>{if(!s.started||s.done)return;const p=point(e);selected=p;});
 $('scene').addEventListener('pointerup',e=>{if(!selected||!s.started||s.done)return;const {x,y}=point(e);selected=null;if(proof===3){const c=Math.floor((x-29)/69),r=Math.floor((y-29)/69);if(c>=0&&c<5&&r>=0&&r<5)action('place',r*5+c);else tel.event('input_error',{reason:'outside_board'});}else if(proof===2){const a=s.animals.find(a=>['roof','raft'].includes(a.status)&&Math.hypot(a.x-x,a.y-y)<38);if(a)action('rescue',a.id);else if(x<125&&y>325)action('bank');}else if(y>140&&y<260)action('take',x>280?1:0);});
 $('scene').addEventListener('pointercancel',()=>{selected=null;tel.event('input_cancelled');});
 document.addEventListener('visibilitychange',()=>{if(document.hidden)tel.leave(s.done);else{last=performance.now();tel.event('page_resumed');}});
 function frame(now){const dt=(now-last)/1000;last=now;if(!document.hidden){const wasBusy=s.busy;tick(s,dt);if(wasBusy>0&&s.busy===0)decisionSince=now;consume();paint.draw(s,now/1000,hover);$('clock').textContent=s.started?Math.max(0,Math.ceil(s.duration-s.t))+'s':'34s';$('clock').className=s.t>26?'danger':'';$('message').textContent=s.message;renderControls();if(s.done&&!finished){finished=true;$('result').hidden=false;$('resultTitle').textContent=proof===1?(s.bank.length?'这一车，留下来了':'宝物还在矿洞深处'):proof===2?(s.bank.length===5?'都到岸上了':'岸边，还有位置'):s.home.damage?'小屋留下了痕迹':'家里，透过了光';$('resultText').textContent=proof===1?`带回 ${s.bank.length} 件，遗落 ${s.lost.length} 件。` : proof===2?`${s.bank.length} 只已到避难岸。其余仍在船、屋顶或浮木上。`:`释放 ${s.home.cleared} 格空间，${s.home.anchors.filter(a=>a.alive).length} 件家具保住了。`;tel.flush();}}requestAnimationFrame(frame);}
 requestAnimationFrame(frame);
}
