// H: a connected outlet, a limited opening window, and actual permanent furniture damage.
export const SHAPES=[[[0,0],[1,0]],[[0,0],[0,1],[1,1]],[[0,0],[1,0],[2,0]],[[0,0],[1,0],[0,1]],[[0,0],[0,1]]];
export function homeState(variant=0){const board=Array(25).fill(0);for(const i of [10,11,15,16,20,21,3,4,8,9,13,14])board[i]=1;return {board,anchors:[{i:6,name:'扶手椅',alive:true},{i:18,name:'落地灯',alive:true}],clean:Array(25).fill(false),piece:variant%3,placed:0,drainCD:0,tide:6,cleared:0,bursts:[],damage:0};}
export function shape(s){let a=SHAPES[s.home.piece%SHAPES.length].map(p=>[...p]);for(let k=0;k<(s.home.rotation||0)%4;k++){a=a.map(([x,y])=>[-y,x]);const minx=Math.min(...a.map(p=>p[0])),miny=Math.min(...a.map(p=>p[1]));a=a.map(([x,y])=>[x-minx,y-miny]);}return a;}
export function fits(s,i){if(!Number.isInteger(i)||i<0||i>=25)return false;const h=s.home,r=Math.floor(i/5),c=i%5;return shape(s).every(([dx,dy])=>r+dy<5&&c+dx<5&&h.board[(r+dy)*5+c+dx]===0&&!h.anchors.some(a=>a.i===(r+dy)*5+c+dx));}
export function connected(s){const b=s.home.board,seen=new Set(),todo=b[20]===1?[20]:[];while(todo.length){const i=todo.pop();if(seen.has(i))continue;seen.add(i);for(const j of [i-5,i+5,...(i%5?[i-1]:[]),...(i%5<4?[i+1]:[])])if(j>=0&&j<25&&b[j]===1&&!seen.has(j))todo.push(j);}return [...seen];}
export function homeAct(s,kind,arg){const h=s.home;if(kind==='place'){if(!fits(s,arg))return {ok:false,reason:'blocked_placement'};for(const [dx,dy] of shape(s))h.board[arg+dy*5+dx]=1;h.piece++;h.placed++;s.message='连起来了。现在排空，还是再接一片？';return {ok:true};}if(kind==='drain'){if(h.drainCD>0)return {ok:false,reason:'drain_cooling'};const ids=connected(s);if(!ids.length)return {ok:false,reason:'outlet_disconnected'};for(const i of ids){h.board[i]=0;h.clean[i]=true;h.bursts.push({i,age:0});}h.cleared+=ids.length;h.drainCD=9;s.flash=.6;s.message=ids.length>8?'整片地板露出来了！下一件有地方了':'空间回来了。排口正在重新蓄力';s.events.push({type:'payoff',kind:'spatial_release',cells:ids.length,t:s.t});return {ok:true};}return {ok:false,reason:'invalid_action'};}
export function incoming(s){const h=s.home,count=3+Math.min(2,Math.floor(s.t/12));const free=h.board.map((v,i)=>v===0&&i%5!==2&&!h.anchors.some(a=>a.i===i)?i:-1).filter(i=>i>=0);return {count,targets:free.slice(-count),damage:free.length<count?h.anchors.find(a=>a.alive):null};}
export function homeTick(s,dt){const h=s.home;h.drainCD=Math.max(0,h.drainCD-dt);h.tide-=dt;for(const b of h.bursts)b.age+=dt;h.bursts=h.bursts.filter(b=>b.age<.8);if(h.tide<=0){h.tide=6;const next=incoming(s);if(!next.damage&&next.targets.length===next.count){const targets=next.targets;for(const i of targets)h.board[i]=1;s.events.push({type:'debris_arrived',cells:targets,t:s.t});s.message='潮水送来木料，下一波会更挤';}else{const a=h.anchors.find(a=>a.alive);if(a){a.alive=false;h.board[a.i]=2;h.damage++;s.flash=.8;s.events.push({type:'owned_object_damaged',object:a.name,t:s.t});s.message=`空间不够，${a.name}被压坏了`;}else{s.done=true;s.events.push({type:'round_end',reason:'room_lost',t:s.t});}}}}
