import {BUILD} from './engine.js';
export class Telemetry{
 constructor(proof,qa){this.proof=proof;this.qa=qa;this.session=crypto.randomUUID();this.rows=[];this.pending=[];this.seq=0;this.acked=0;this.status='waiting';this.newRun(false);}
 newRun(replay=true){this.run=crypto.randomUUID();this.runStart=performance.now();this.actions=0;this.payoffAt=null;this.lastAction=null;this.lastChoice=null;this.event(replay?'voluntary_retry':'proof_view',{retry_prompt:'neutral_button_only'});}
 event(name,props={}){const id=crypto.randomUUID();const row={event:'mission003_'+name,uuid:id,distinct_id:this.session,timestamp:new Date().toISOString(),properties:{event_id:id,mission:'MISSION003',proof:this.proof,build:BUILD,session_id:this.session,run_id:this.run,qa:this.qa,sequence:++this.seq,run_elapsed_ms:Math.round(performance.now()-this.runStart),$process_person_profile:false,$geoip_disable:true,$ip:null,...props}};this.rows.push(row);this.pending.push(row);this.onchange?.();return row;}
 action(kind,props={}){const now=performance.now();this.actions++;this.event('action',{kind,action_index:this.actions,time_to_first_action_ms:this.actions===1?Math.round(now-this.runStart):null,after_payoff_ms:this.payoffAt===null?null:Math.round(now-this.payoffAt),unprompted_status:'UNKNOWN_REQUIRES_OBSERVER',...props});if(this.lastChoice&&this.lastChoice!==kind)this.event('choice_change',{from:this.lastChoice,to:kind,meaning:'different_action_not_proof_of_reversed_intent'});this.lastChoice=kind;this.lastAction=now;}
 payoff(props){this.event('payoff',{time_to_payoff_ms:Math.round(performance.now()-this.runStart),...props});this.payoffAt=performance.now();}
 async flush(){if(this.busy||!this.pending.length)return;const c=window.PROOF_ANALYTICS;if(!c?.host||!c?.token){this.status='not_configured';return;}this.busy=true;try{while(this.pending.length){const rows=this.pending.slice(0,20);const r=await fetch(c.host+'/batch/',{method:'POST',headers:{'Content-Type':'text/plain'},body:JSON.stringify({api_key:c.token,batch:rows}),keepalive:true,signal:AbortSignal.timeout(8000)});if(!r.ok)throw Error('HTTP_'+r.status);const ack=await r.json();if(ack!==1&&ack!=='1'&&ack?.status!==1&&String(ack?.status).toLowerCase()!=='ok')throw Error('ack_missing');this.pending.splice(0,rows.length);this.acked+=rows.length;}this.status='ingestion_acknowledged';this.error=null;}catch(e){this.error=e.message;this.status='retry_pending';}finally{this.busy=false;this.onchange?.();}}
 leave(done){this.event('page_hidden',{quit_before_payoff:this.payoffAt===null,round_done:done,action_count:this.actions,exit_status:'visibility_only_not_confirmed_quit'});this.flush();}
}
