import{Base,W,H}from'../gen2-shared/craft.js';import{create,step,grab,move,release,drain}from'./model.mjs';
const skins=['gold','jade','pink'];
class Squeeze extends Base{
 create(){this.setup('g22','挤出连合','推近相同纹路');this.world=this.add.container(0,0);this.accumulator=0;this.pointerId=null;this.reset();this.input.on('pointerdown',p=>{if(this.records||this.pointerId!==null||p.y<200||p.y>680)return;const id=grab(this.model,p.x,p.y);if(id===false)return;this.pointerId=p.id;this.origin={x:p.x,y:p.y};this.dragDistance=0;this.tel.emit('drag_start','player',{body:id});this.ring(p.x,p.y,0xffdebd);this.caption.setText('');});this.input.on('pointermove',p=>{if(p.id!==this.pointerId||!p.isDown)return;this.dragDistance=Math.max(this.dragDistance,Math.hypot(p.x-this.origin.x,p.y-this.origin.y));move(this.model,p.x,p.y);});this.input.on('pointerup',p=>{if(p.id!==this.pointerId)return;if(this.dragDistance>6)this.tel.action('push_end',{distance:Math.round(this.dragDistance),remaining:this.model.bodies.length,merges:this.model.merges,lost:this.model.gutter.length});release(this.model);this.pointerId=null;this.tel.flush();});}
 reset(){this.world.removeAll(true);this.model=create();this.pointerId=null;this.visuals=new Map();this.caption.setText('推近相同纹路');const back=this.add.graphics();back.fillGradientStyle(0xb4c0aa,0x829d91,0x5e7875,0x9eaf98,1).fillRoundedRect(39,218,312,411,50);back.lineStyle(10,0x0c1a23,.85).strokeRoundedRect(33,211,324,426,54);back.lineStyle(2,0xd6d6b7,.6).strokeRoundedRect(39,218,312,411,50);back.lineStyle(1,0x314f4e,.4);for(let y=248;y<611;y+=13)back.lineBetween(66,y,324,y);for(let i=0;i<6;i++){back.fillStyle(0x07131b,.65).fillRoundedRect(14,273+i*49,11,29,5);back.fillRoundedRect(365,273+i*49,11,29,5);}back.fillStyle(0x030d15,.8).fillRoundedRect(35,641,320,31,12);back.lineStyle(1,0x7a8e8a,.4).strokeRoundedRect(35,641,320,31,12);this.world.add(back);this.world.add(this.add.image(195,423.5,'tray').setDisplaySize(312,411));const sign=this.add.graphics();sign.lineStyle(1,0xc1c9b4,.4).strokeCircle(195,167,21);sign.lineStyle(2,0xd6dcbd,.6).lineBetween(184,167,206,167);sign.lineBetween(201,162,206,167);sign.lineBetween(201,172,206,167);this.world.add(sign);this.edge=this.add.graphics().setDepth(26);this.world.add(this.edge);this.tel.emit('ready','system',{bodies:12});this.sync();}
 makeBody(b){const shadow=this.add.image(0,b.r*.65,'shadow').setDisplaySize(b.r*2.55,b.r*.65),stone=this.add.image(0,0,skins[b.level]).setDisplaySize(b.r*2.42,b.r*2.42);const marks=this.add.graphics();marks.lineStyle(2,0xfff6df,.58);if(b.level===0){marks.fillStyle(0xfff9d7,.75).fillCircle(0,0,4);}else if(b.level===1){marks.beginPath().moveTo(-13,2).quadraticBezierTo?.(0,-9,13,2);marks.lineBetween(-12,2,0,-5);marks.lineBetween(0,-5,12,2);}else{marks.strokeCircle(0,0,10);marks.strokeCircle(0,0,5);}const v=this.add.container(b.x,b.y,[shadow,stone,marks]);this.world.add(v);this.visuals.set(b.id,{v,stone,r:b.r});return this.visuals.get(b.id);}
 sync(){const ids=new Set(this.model.bodies.map(b=>b.id));for(const[id,o]of this.visuals){if(!ids.has(id)){o.v.destroy();this.visuals.delete(id);}}this.edge.clear();for(const b of this.model.bodies){const o=this.visuals.get(b.id)||this.makeBody(b);o.v.setPosition(b.x,b.y);const held=b.id===this.model.drag;const speed=Math.min(1,Math.hypot(b.vx,b.vy)/220),birth=Math.sin(Math.min(1,(this.model.time-b.born)/.17)*Math.PI);o.stone.setScale(b.r*2.42/256*(held?1.03:1)*(1+speed*.04+birth*.15),b.r*2.42/256*(held?.98:1)*(1-birth*.12));if(held){this.world.bringToTop(o.v);const dx=this.model.target.x-b.x,dy=this.model.target.y-b.y;this.edge.lineStyle(2,0xffe1a0,.42).lineBetween(b.x,b.y,b.x+dx*.25,b.y+dy*.25);}if(b.x-b.r<48||b.x+b.r>342||b.y+b.r>619||b.y-b.r<228){this.edge.lineStyle(3,0xe7ab67,.5).strokeCircle(b.x,b.y,b.r+3);}}}
 update(_,delta){if(!this.model)return;this.accumulator+=Math.min(delta/1000,.05);while(this.accumulator>=1/180){step(this.model,1/180);this.accumulator-=1/180;for(const e of drain(this.model)){if(e.type==='merge'){this.burst(e.x,e.y,true);this.tone('merge');this.ring(e.x,e.y,0xffe5b6);this.tel.reward('contact_merge',{...e,geometry_contact:true});if(e.level===3){const token=this.add.image(e.x,e.y,'pink').setDisplaySize(101,30).setAlpha(.6);this.world.addAt(token,3);this.tweens.add({targets:token,alpha:.45,scaleY:.05,duration:350});}}else if(e.type==='gutter'){const ghost=this.add.image(e.x,e.y,skins[e.level]).setDisplaySize(50,50).setTint(0x9baaaa).setDepth(30);this.world.add(ghost);this.tweens.add({targets:ghost,x:48+(this.model.gutter.length-1)*26,y:656,alpha:.55,scaleX:29/256,scaleY:22/256,duration:250,ease:'Cubic.In'});this.caption.setText('出盘的石，留在槽里');this.tone('impact');this.tel.emit('boundary_loss','automatic',e);}}}this.sync();}
 readableState(){return{time:+this.model.time.toFixed(2),merges:this.model.merges,remaining:this.model.bodies.length,lost:this.model.gutter.map(b=>b.id),settled:this.model.completed.length,drag:this.model.drag,bodies:this.model.bodies.map(b=>b.id+":L"+b.level+"@"+Math.round(b.x)+","+Math.round(b.y)),sound:this.audio?.state||'off'};}
 cancel(){if(this.model)release(this.model);this.pointerId=null;this.tel?.emit('input_cancel','player');}
}
new Phaser.Game({type:Phaser.AUTO,parent:'game',width:W,height:H,backgroundColor:'#101820',antialias:true,scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},input:{activePointers:2},scene:Squeeze});
