export const radius=[27,27*Math.sqrt(1.7),27*1.7];
const seed=[[0,110,285],[0,250,285],[1,180,285],[2,95,408],[1,180,385],[0,285,385],[0,285,445],[2,175,485],[1,85,490],[2,285,550],[1,85,570],[2,185,585]];
export function create(){return{time:0,nextId:12,bodies:seed.map(([level,x,y],id)=>({id,level,x,y,vx:0,vy:0,r:radius[level],born:0})),drag:null,target:null,gutter:[],completed:[],events:[],merges:0};}
export function grab(s,x,y){if(s.drag!==null)return false;const b=[...s.bodies].reverse().find(b=>Math.hypot(b.x-x,b.y-y)<=b.r+5);if(!b)return false;s.drag=b.id;s.target={x,y};return b.id;}
export function move(s,x,y){if(s.drag===null)return;s.target={x:Math.max(5,Math.min(385,x)),y:Math.max(165,Math.min(681,y))};}
export function release(s){s.drag=null;s.target=null;}
export function step(s,dt){s.time+=dt;for(const b of s.bodies){if(b.id===s.drag&&s.target){const dx=s.target.x-b.x,dy=s.target.y-b.y;let tx=dx*9,ty=dy*9,mag=Math.hypot(tx,ty);if(mag>220){tx*=220/mag;ty*=220/mag;}b.vx+=(tx-b.vx)*Math.min(1,dt*24);b.vy+=(ty-b.vy)*Math.min(1,dt*24);}else{b.vx*=Math.exp(-5*dt);b.vy*=Math.exp(-5*dt);}b.x+=b.vx*dt;b.y+=b.vy*dt;}
 for(let pass=0;pass<5;pass++)for(let i=0;i<s.bodies.length;i++)for(let j=i+1;j<s.bodies.length;j++){const a=s.bodies[i],b=s.bodies[j],dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy)||.001,sum=a.r+b.r;if(d>sum+.3)continue;const nx=dx/d,ny=dy/d,rel=Math.hypot(a.vx-b.vx,a.vy-b.vy);if(a.level===b.level){const area=a.r*a.r+b.r*b.r,x=(a.x*a.r*a.r+b.x*b.r*b.r)/area,y=(a.y*a.r*a.r+b.y*b.r*b.r)/area,id=s.nextId++;s.merges++;s.events.push({type:'merge',a:a.id,b:b.id,id,level:a.level+1,x,y,areaBefore:Math.PI*area,areaAfter:a.level===2?0:Math.PI*area*.85,relativeSpeed:rel});s.bodies=s.bodies.filter(v=>v!==a&&v!==b);if(a.level===2){s.completed.push({id,x,y,level:3});if(s.drag===a.id||s.drag===b.id)release(s);}else{const n={id,level:a.level+1,x,y,vx:(a.vx+b.vx)*.25,vy:(a.vy+b.vy)*.25,r:Math.sqrt(area*.85),born:s.time};s.bodies.push(n);if(s.drag===a.id||s.drag===b.id)s.drag=id;}i=-1;break;}
 if(d>=sum)continue;const ia=(a.id===s.drag ? .45:1)/(a.r*a.r),ib=(b.id===s.drag ? .45:1)/(b.r*b.r),overlap=sum-d,weight=ia+ib;a.x-=nx*overlap*ia/weight;a.y-=ny*overlap*ia/weight;b.x+=nx*overlap*ib/weight;b.y+=ny*overlap*ib/weight;const vn=(b.vx-a.vx)*nx+(b.vy-a.vy)*ny;if(vn<0){const impulse=-1.08*vn/weight;a.vx-=impulse*nx*ia;a.vy-=impulse*ny*ia;b.vx+=impulse*nx*ib;b.vy+=impulse*ny*ib;}}
 for(const b of [...s.bodies]){if(b.x<45-b.r*.25||b.x>345+b.r*.25||b.y<225-b.r*.25||b.y>620+b.r*.25){s.bodies=s.bodies.filter(v=>v!==b);s.gutter.push({...b});s.events.push({type:'gutter',id:b.id,level:b.level,x:b.x,y:b.y});if(s.drag===b.id)release(s);}}}
export function drain(s){return s.events.splice(0);}
