import{create,start,pause,resume,step}from'./engine.mjs';import{loadArt,paint}from'./paint.js';import{createAudio}from'./audio.js';
const $=id=>document.getElementById(id),canvas=$('canvas'),ctx=canvas.getContext('2d'),audio=createAudio();let state=create(),art=null,target=null,pointer=null,last=performance.now(),acc=0,seen=new Set(),ui='',qaAt=0,volley=0;
const qa=new URLSearchParams(location.search).get('qa')==='1';if(qa)$('qa').classList.remove('hidden');
function clear(){target=null;pointer=null;acc=0}
function suspend(reason){clear();pause(state,reason);audio.stop();sync()}
function sync(){if(ui===state.status)return;ui=state.status;$('overlay').classList.toggle('hidden',ui==='playing');$('pause').disabled=ui!=='playing';$('tag').textContent=ui==='won'?'你的火力，开出了一条路。':ui==='lost'?'再来一次，换条路线。':ui==='paused'?'随时可以继续。':'把他们的火力，变成你的。';$('title').textContent=ui==='won'?'突围成功':ui==='lost'?'车辆损毁':ui==='paused'?'已暂停':'夺械突围';$('copy').innerHTML=ui==='won'?`${Math.round(state.t)} 秒 · 击破 ${state.kills} 辆<br>下次，试试另一种夺炮路线。`:ui==='lost'?`${state.cause}<br>躲开红色瞄准线，让敌人落在车侧。`:ui==='paused'?'车辆和战场都在等你。':'拖动车辆 · 靠近夺炮<br>击破 4 辆，撑到出口亮起。';$('action').textContent=ui==='paused'?'继续突围':ui==='lost'||ui==='won'?'再闯一次':'开始突围'}
$('action').onclick=()=>{if(!art)return;clear();audio.play('retry');if(state.status==='paused')resume(state);else{state=create();seen.clear();volley=0;start(state)}last=performance.now();sync()};$('pause').onclick=()=>suspend('button');$('sound').onclick=()=>{const m=audio.toggle();$('sound').textContent=m?'声音 关':'声音 开';$('sound').setAttribute('aria-label',m?'开启声音':'关闭声音');if(!m)audio.play('contact')};
function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*390/r.width,y:(e.clientY-r.top)*760/r.height-(e.pointerType==='touch'?38:0)}}
canvas.onpointerdown=e=>{if(state.status!=='playing'||pointer!==null)return;e.preventDefault();pointer=e.pointerId;canvas.setPointerCapture(pointer);target=point(e)};canvas.onpointermove=e=>{if(e.pointerId===pointer)target=point(e)};canvas.onpointerup=e=>{if(e.pointerId===pointer)clear()};canvas.onpointercancel=e=>{if(e.pointerId===pointer)clear()};canvas.onlostpointercapture=e=>{if(e.pointerId===pointer)clear()};document.addEventListener('visibilitychange',()=>{if(document.hidden)suspend('hidden')});window.addEventListener('blur',()=>suspend('blur'));window.addEventListener('resize',()=>{if(state.status==='playing')suspend('resize');else clear()});
loadArt().then(a=>{art=a;$('action').disabled=false;sync()}).catch(e=>{$('error').classList.remove('hidden');$('error').textContent=e.message+'。请重新加载。';$('action').textContent='素材未就绪';});
function frame(now){let dt=(now-last)/1000;last=now;if(dt>.25&&state.status==='playing')suspend('long-frame');if(state.status==='playing'){acc+=Math.min(dt,.1);while(acc>=1/120){step(state,1/120,target);acc-=1/120}if(state.volley!==volley){volley=state.volley;audio.play(state.lastWeapon)}for(const e of state.events){if(seen.has(e))continue;seen.add(e);if(e.type==='capture')audio.play('convergence');if(e.type==='destroy')audio.play('cut');if(e.type==='damage')audio.play('failure');if(e.type==='won'||e.type==='exit-open')audio.play('restoration')}if(seen.size>300)seen=new Set(state.events)}paint(ctx,state,art,target);sync();if(qa&&now-qaAt>200){qaAt=now;$('qa').textContent=JSON.stringify({build:state.build,status:state.status,t:+state.t.toFixed(2),p:state.p,kills:state.kills,covers:state.covers,enemyCount:state.enemies.length,shotCount:state.shots.length,enemies:state.enemies.map(e=>({x:e.x,y:e.y,r:e.r,entry:e.entry})),hostileShots:state.shots.filter(b=>b.enemy).map(b=>({x:b.x,y:b.y,vx:b.vx,vy:b.vy,r:b.r})),events:state.events},null,2)}requestAnimationFrame(frame)}requestAnimationFrame(frame);




